tags = {
    "eat_and_drink": {"amenity": "restaurant"},
    "restaurant": {"amenity": "restaurant"},
    "afghan_restaurant": {"amenity": "restaurant", "cuisine": "afghan"},
    "african_restaurant": {"amenity": "restaurant", "cuisine": "african"},
    "ethiopian_restaurant": {"amenity": "restaurant", "cuisine": "ethiopian"},
    "senegalese_restaurant": {"amenity": "restaurant", "cuisine": "senegalese"},
    "south_african_restaurant": {"amenity": "restaurant"},
    "moroccan_restaurant": {"amenity": "restaurant", "cuisine": "moroccan"},
    "nigerian_restaurant": {"amenity": "restaurant"},
    "american_restaurant": {"amenity": "restaurant", "cuisine": "american"},
    "arabian_restaurant": {"amenity": "restaurant", "cuisine": "arab"},
    "belgian_restaurant": {"amenity": "restaurant", "cuisine": "belgian"},
    "latin_american_restaurant": {"amenity": "restaurant", "cuisine": "latin_american"},
    "argentine_restaurant": {"amenity": "restaurant", "cuisine": "argentinian"},
    "belizean_restaurant": {"amenity": "restaurant"},
    "bolivian_restaurant": {"amenity": "restaurant", "cuisine": "bolivian"},
    "brazilian_restaurant": {"amenity": "restaurant", "cuisine": "brazilian"},
    "chilean_restaurant": {"amenity": "restaurant"},
    "colombian_restaurant": {"amenity": "restaurant", "cuisine": "colombian"},
    "costa_rican_restaurant": {"amenity": "restaurant"},
    "cuban_restaurant": {"amenity": "restaurant", "cuisine": "cuban"},
    "ecuadorian_restaurant": {"amenity": "restaurant"},
    "guatemalan_restaurant": {"amenity": "restaurant"},
    "honduran_restaurant": {"amenity": "restaurant"},
    "mexican_restaurant": {"amenity": "restaurant", "cuisine": "mexican"},
    "nicaraguan_restaurant": {"amenity": "restaurant"},
    "panamanian_restaurant": {"amenity": "restaurant"},
    "paraguayan_restaurant": {"amenity": "restaurant"},
    "peruvian_restaurant": {"amenity": "restaurant", "cuisine": "peruvian"},
    "puerto_rican_restaurant": {"amenity": "restaurant"},
    "salvadoran_restaurant": {"amenity": "restaurant"},
    "texmex_restaurant": {"amenity": "restaurant", "cuisine": "tex-mex"},
    "uruguayan_restaurant": {"amenity": "restaurant"},
    "venezuelan_restaurant": {"amenity": "restaurant", "cuisine": "venezuelan"},
    "middle_eastern_restaurant": {"amenity": "restaurant", "cuisine": "middle_eastern"},
    "armenian_restaurant": {"amenity": "restaurant", "cuisine": "armenian"},
    "azerbaijani_restaurant": {"amenity": "restaurant"},
    "egyptian_restaurant": {"amenity": "restaurant", "cuisine": "egyptian"},
    "georgian_restaurant": {"amenity": "restaurant", "cuisine": "georgian"},
    "kofta_restaurant": {"amenity": "restaurant"},
    "kurdish_restaurant": {"amenity": "restaurant"},
    "lebanese_restaurant": {"amenity": "restaurant", "cuisine": "lebanese"},
    "persian_iranian_restaurant": {"amenity": "restaurant", "cuisine": "persian"},
    "syrian_restaurant": {"amenity": "restaurant", "cuisine": "syrian"},
    "turkish_restaurant": {"amenity": "restaurant", "cuisine": "turkish"},
    "asian_restaurant": {"amenity": "restaurant", "cuisine": "asian"},
    "asian_fusion_restaurant": {"amenity": "restaurant", "cuisine": "fusion"},
    "pan_asian_restaurant": {"amenity": "restaurant"},
    "burmese_restaurant": {"amenity": "restaurant"},
    "cambodian_restaurant": {"amenity": "restaurant", "cuisine": "cambodian"},
    "chinese_restaurant": {"amenity": "restaurant", "cuisine": "chinese"},
    "dim_sum_restaurant": {"amenity": "restaurant"},
    "filipino_restaurant": {"amenity": "restaurant", "cuisine": "filipino"},
    "indo_chinese_restaurant": {"amenity": "restaurant"},
    "indonesian_restaurant": {"amenity": "restaurant", "cuisine": "indonesian"},
    "japanese_restaurant": {"amenity": "restaurant", "cuisine": "japanese"},
    "korean_restaurant": {"amenity": "restaurant", "cuisine": "korean"},
    "sushi_restaurant": {"amenity": "restaurant", "cuisine": "sushi"},
    "laotian_restaurant": {"amenity": "restaurant"},
    "malaysian_restaurant": {"amenity": "restaurant", "cuisine": "malaysian"},
    "mongolian_restaurant": {"amenity": "restaurant", "cuisine": "mongolian"},
    "noodles_restaurant": {"amenity": "restaurant", "cuisine": "noodle"},
    "singaporean_restaurant": {"amenity": "restaurant", "cuisine": "singaporean"},
    "taiwanese_restaurant": {"amenity": "restaurant", "cuisine": "taiwanese"},
    "thai_restaurant": {"amenity": "restaurant", "cuisine": "thai"},
    "vietnamese_restaurant": {"amenity": "restaurant", "cuisine": "vietnamese"},
    "australian_restaurant": {"amenity": "restaurant", "cuisine": "australian"},
    "austrian_restaurant": {"amenity": "restaurant", "cuisine": "austrian"},
    "bangladeshi_restaurant": {"amenity": "restaurant", "cuisine": "bangladeshi"},
    "indian_restaurant": {"amenity": "restaurant", "cuisine": "indian"},
    "basque_restaurant": {"amenity": "restaurant", "cuisine": "basque"},
    "british_restaurant": {"amenity": "restaurant", "cuisine": "british"},
    "eastern_european_restaurant": {
        "amenity": "restaurant",
        "cuisine": "middle_eastern",
    },
    "belarusian_restaurant": {"amenity": "restaurant"},
    "bulgarian_restaurant": {"amenity": "restaurant", "cuisine": "bulgarian"},
    "romanian_restaurant": {"amenity": "restaurant", "cuisine": "romanian"},
    "tatar_restaurant": {"amenity": "restaurant"},
    "ukrainian_restaurant": {"amenity": "restaurant", "cuisine": "ukrainian"},
    "french_restaurant": {"amenity": "restaurant", "cuisine": "french"},
    "cajun_creole_restaurant": {"amenity": "restaurant", "cuisine": "cajun"},
    "canadian_restaurant": {"amenity": "restaurant"},
    "caribbean_restaurant": {"amenity": "restaurant", "cuisine": "caribbean"},
    "dominican_restaurant": {"amenity": "restaurant"},
    "haitian_restaurant": {"amenity": "restaurant"},
    "jamaican_restaurant": {"amenity": "restaurant", "cuisine": "jamaican"},
    "trinidadian_restaurant": {"amenity": "restaurant"},
    "german_restaurant": {"amenity": "restaurant", "cuisine": "german"},
    "catalan_restaurant": {"amenity": "restaurant"},
    "italian_restaurant": {"amenity": "restaurant", "cuisine": "italian"},
    "czech_restaurant": {"amenity": "restaurant", "cuisine": "czech"},
    "mediterranean_restaurant": {"amenity": "restaurant", "cuisine": "mediterranean"},
    "greek_restaurant": {"amenity": "restaurant", "cuisine": "greek"},
    "guamanian_restaurant": {"amenity": "restaurant"},
    "hawaiian_restaurant": {"amenity": "restaurant", "cuisine": "hawaiian"},
    "himalayan_nepalese_restaurant": {"amenity": "restaurant"},
    "hungarian_restaurant": {"amenity": "restaurant", "cuisine": "hungarian"},
    "iberian_restaurant": {"amenity": "restaurant"},
    "irish_restaurant": {"amenity": "restaurant"},
    "jewish_restaurant": {"amenity": "restaurant"},
    "international_restaurant": {"amenity": "restaurant"},
    "european_restaurant": {"amenity": "restaurant"},
    "oriental_restaurant": {"amenity": "restaurant"},
    "pakistani_restaurant": {"amenity": "restaurant"},
    "polish_restaurant": {"amenity": "restaurant"},
    "polynesian_restaurant": {"amenity": "restaurant"},
    "portuguese_restaurant": {"amenity": "restaurant"},
    "russian_restaurant": {"amenity": "restaurant"},
    "scandinavian_restaurant": {"amenity": "restaurant"},
    "danish_restaurant": {"amenity": "restaurant"},
    "norwegian_restaurant": {"amenity": "restaurant"},
    "scottish_restaurant": {"amenity": "restaurant"},
    "seafood_restaurant": {"amenity": "restaurant", "cuisine": "seafood"},
    "serbo_croation_restaurant": {"amenity": "restaurant"},
    "slovakian_restaurant": {"amenity": "restaurant"},
    "southern_restaurant": {"amenity": "restaurant"},
    "spanish_restaurant": {"amenity": "restaurant"},
    "sri_lankan_restaurant": {"amenity": "restaurant"},
    "swiss_restaurant": {"amenity": "restaurant"},
    "uzbek_restaurant": {"amenity": "restaurant"},
    "molecular_gastronomy_restaurant": {"amenity": "restaurant"},
    "haute_cuisine_restaurant": {"amenity": "restaurant"},
    "buffet_restaurant": {"amenity": "restaurant"},
    "barbecue_restaurant": {"amenity": "restaurant"},
    "burger_restaurant": {"amenity": "restaurant", "cuisine": "burger"},
    "cafetaria": {"amenity": "fast_food", "fast_food": "cafeteria"},
    "cheesesteak_restaurant": {"amenity": "restaurant"},
    "chicken_restaurant": {"amenity": "restaurant"},
    "chicken_wings_restaurant": {"amenity": "restaurant"},
    "dog_meat_restaurant": {"amenity": "restaurant"},
    "dumpling_restaurant": {"amenity": "restaurant"},
    "fast_food_restaurant": {"amenity": "fast_food"},
    "fishchbroetchen_restaurant": {"amenity": "restaurant"},
    "fish_restaurant": {"amenity": "restaurant"},
    "fish_and_chips_restaurant": {"amenity": "restaurant"},
    "fondue_restaurant": {"amenity": "restaurant"},
    "gluten_free_restaurant": {"amenity": "restaurant"},
    "baozi_restaurant": {"amenity": "restaurant"},
    "halal_restaurant": {"amenity": "restaurant"},
    "health_food_restaurant": {"amenity": "restaurant"},
    "kosher_restaurant": {"amenity": "restaurant"},
    "comfort_food_restaurant": {"amenity": "restaurant"},
    "meat_restaurant": {"amenity": "restaurant"},
    "curry_sausage_restaurant": {"amenity": "restaurant"},
    "food_court": {"amenity": "food_court"},
    "pizza_restaurant": {"amenity": "restaurant", "cuisine": "pizza"},
    "vegan_restaurant": {"amenity": "restaurant", "diet:vegan": "yes"},
    "vegetarian_restaurant": {"amenity": "restaurant", "diet:vegetarian": "yes"},
    "steakhouse": {"amenity": "restaurant", "cuisine": "steak_house"},
    "bar": {"amenity": "bar"},
    "beer_garden": {"amenity": "biergarten"},
    "bubble_tea": {"amenity": "cafe", "cuisine": "bubble_tea"},
    "pub": {"amenity": "pub"},
    "cafe": {"amenity": "cafe"},
    "coffee_shop": {"amenity": "cafe", "cuisine": "coffee_shop"},
    "accommodation": {"tourism": "yes"},
    "bed_and_breakfast": {"tourism": "guest_house", "guest_house": "bed_and_breakfast"},
    "cabin": {"tourism": "chalet"},
    "campground": {"tourism": "camp_site"},
    "cottage": {"tourism": "chalet"},
    "guest_house": {"tourism": "guest_house"},
    "hostel": {"tourism": "hostel"},
    "hotel": {"tourism": "hotel"},
    "motel": {"tourism": "motel"},
    "resort": {"leisure": "resort"},
    "beach_resort": {"leisure": "beach_resort"},
    "rv_park": {"tourism": "caravan_site"},
    "service_apartments": {"tourism": "apartment"},
    "automotive_dealer": {"shop": "car"},
    "car_dealer": {"shop": "car"},
    "motorcycle_dealer": {"shop": "motorcycle"},
    "used_car_dealer": {"shop": "car", "second_hand": "only"},
    "car_wash": {"amenity": "car_wash"},
    "motorcycle_repair": {"shop": "motorcycle_repair"},
    "tire_dealer_and_repair": {"shop": "tyres"},
    "automotive_parts_and_accessories": {"shop": "car_parts"},
    "gas_station": {"amenity": "fuel"},
    "truck_gas_station": {"amenity": "fuel", "hgv": "yes"},
    "ev_charging_station": {"amenity": "charging_station"},
    "automotive_repair": {"shop": "car_repair"},
    "bookmakers": {"shop": "bookmaker"},
    "carousel": {"attraction": "carousel"},
    "casino": {"amenity": "casino"},
    "internet_cafe": {"amenity": "internet_cafe"},
    "paintball": {"leisure": "pitch", "sport": "paintball"},
    "planetarium": {"amenity": "planetarium"},
    "baseball_stadium": {"leisure": "pitch", "sport": "baseball"},
    "basketball_stadium": {"leisure": "pitch", "sport": "basketball"},
    "cricket_ground": {"leisure": "pitch", "sport": "cricket"},
    "football_stadium": {"leisure": "pitch", "sport": "american_football"},
    "soccer_stadium": {"leisure": "pitch", "sport": "soccer"},
    "tennis_stadium": {"leisure": "pitch", "sport": "tennis"},
    "theatre": {"amenity": "theatre"},
    "water_park": {"leisure": "water_park"},
    "cinema": {"amenity": "cinema"},
    "psychic": {"shop": "psychic"},
    "amusement_park": {"tourism": "theme_park"},
    "aquarium": {"tourism": "aquarium"},
    "art_gallery": {"tourism": "gallery"},
    "beach": {"natural": "beach"},
    "botanical_garden": {"leisure": "garden", "garden:type": "botanical"},
    "castle": {"historic": "castle"},
    "fort": {"historic": "fort"},
    "fountain": {"amenity": "fountain"},
    "lake": {"natural": "water", "water": "lake"},
    "lighthouse": {"man_made": "lighthouse"},
    "marina": {"leisure": "marina"},
    "monument": {"historic": "monument"},
    "observatory": {"man_made": "observatory"},
    "palace": {"historic": "castle", "castle_type": "palace"},
    "plaza": {"place": "square"},
    "ruin": {"historic": "ruins"},
    "waterfall": {"waterway": "waterfall"},
    "zoo": {"tourism": "zoo"},
    "petting_zoo": {"tourism": "zoo", "zoo": "petting_zoo"},
    "museum": {"tourism": "museum"},
    "park": {"leisure": "park"},
    "dog_park": {"leisure": "dog_park"},
    "archery_range": {"leisure": "pitch", "sport": "archery"},
    "bowling_alley": {"leisure": "bowling_alley"},
    "disc_golf_course": {"leisure": "disc_golf_course"},
    "golf_course": {"leisure": "golf_course"},
    "driving_range": {"golf": "driving_range"},
    "gym": {"leisure": "fitness_centre"},
    "horse_riding": {"leisure": "horse_riding"},
    "miniature_golf_course": {"leisure": "miniature_golf"},
    "playground": {"leisure": "playground"},
    "swimming_pool": {"leisure": "swimming_pool"},
    "trampoline_park": {"leisure": "trampoline_park"},
    "beauty_salon": {"shop": "beauty"},
    "barber": {"shop": "hairdresser"},
    "massage": {"shop": "massage"},
    "tattoo_and_piercing": {"shop": "tattoo", "piercing": "yes"},
    "piercing": {"shop": "tattoo", "piercing": "yes"},
    "tattoo": {"shop": "tattoo"},
    "college_university": {"amenity": "university"},
    "school": {"amenity": "school"},
    "elementary_school": {"amenity": "school"},
    "high_school": {"amenity": "school"},
    "driving_school": {"amenity": "driving_school"},
    "language_school": {"amenity": "language_school"},
    "music_school": {"amenity": "music_school"},
    "financial_service": {"office": "financial"},
    "accountant": {"office": "accountant"},
    "atms": {"amenity": "atm"},
    "bank_credit_union": {"amenity": "bank"},
    "banks": {"amenity": "bank"},
    "insurance_agency": {"office": "insurance"},
    "private_establishments_and_corporates": {"office": "company"},
    "retail": {"shop": "yes"},
    "bakery": {"shop": "bakery"},
    "ice_cream_shop": {"amenity": "ice_cream"},
    "liquor_store": {"shop": "alcohol"},
    "winery": {"craft": "winery"},
    "butcher_shop": {"shop": "butcher"},
    "carpet_store": {"shop": "carpet"},
    "distillery": {"craft": "distillery"},
    "pharmacy": {"amenity": "pharmacy"},
    "bookstore": {"shop": "books"},
    "clothing_store": {"shop": "clothes"},
    "men's_clothing_store": {"shop": "clothes", "clothes": "men"},
    "women's_clothing_store": {"shop": "clothes", "clothes": "women"},
    "fashion_accessories_store": {"shop": "fashion_accessories"},
    "shoe_store": {"shop": "shoes"},
    "eyewear_and_optician": {"shop": "optician"},
    "flowers_and_gifts_shop": {"shop": "flowers"},
    "florist": {"shop": "florist"},
    "grocery_store": {"shop": "convenience"},
    "hardware_store": {"shop": "hardware"},
    "furniture_store": {"shop": "furniture"},
    "home_improvement_store": {"shop": "diy"},
    "medical_supply": {"shop": "medical_supply"},
    "hearing_aids": {"shop": "hearing_aids"},
    "pet_store": {"shop": "pet"},
    "computer_store": {"shop": "computer"},
    "convenience_store": {"shop": "convenience"},
    "department_store": {"shop": "department_store"},
    "discount_store": {"shop": "discount"},
    "electronics": {"shop": "electronics"},
    "jewelry_store": {"shop": "jewelry"},
    "mobile_phone_store": {"shop": "mobile_phone"},
    "shopping_center": {"shop": "mall"},
    "supermarket": {"shop": "supermarket"},
    "superstore": {"shop": "supermarket"},
    "bicycle_shop": {"shop": "bicycle"},
    "health_and_medical": {"healthcare": "yes"},
    "psychotherapist": {"healthcare": "psychotherapist"},
    "dentist": {"amenity": "dentist"},
    "doctor": {"amenity": "doctor"},
    "audiologist": {"healthcare": "audiologist"},
    "fertility": {
        "amenity": "clinic",
        "healthcare": "clinic",
        "healthcare:speciality": "fertility",
    },
    "podiatrist": {"healthcare": "podiatrist"},
    "acupuncture": {
        "healthcare": "alternative",
        "healthcare:speciality": "acupuncture",
    },
    "ayurveda": {"healthcare": "alternative", "healthcare:speciality": "ayurveda"},
    "halotherapy": {"healthcare:speciality": "halotherapy"},
    "hospice": {"healthcare": "hospice"},
    "hospital": {"amenity": "hospital"},
    "midwife": {"healthcare": "midwife"},
    "optometrist": {"healthcare": "optometrist"},
    "podiatry": {"amenity": "doctors", "healthcare:speciality": "podiatry"},
    "sauna": {"leisure": "sauna"},
    "speech_therapist": {"healthcare": "speech_therapist"},
    "psychiatrist": {"amenity": "doctors", "healthcare:speciality": "psychiatry"},
    "traditional_chinese_medicine": {
        "healthcare": "alternative",
        "healthcare:speciality": "traditional_chinese_medicine",
    },
    "pet_groomer": {"shop": "pet_grooming"},
    "animal_shelter": {"amenity": "animal_shelter"},
    "veterinarian": {"amenity": "veterinary"},
    "business_to_business": {"office": "yes"},
    "research_institute": {"amenity": "research_institute"},
    "coworking_space": {"amenity": "coworking_space"},
    "public_service_and_government": {"office": "yes"},
    "charity_organization": {"office": "charity"},
    "homeless_shelter": {
        "amenity": "social_facility",
        "social_facility": "shelter",
        "social_facility:for": "homeless",
    },
    "post_office": {"amenity": "post_office"},
    "community_center": {"amenity": "community_centre"},
    "courthouse": {"amenity": "courthouse"},
    "embassy": {"office": "diplomatic", "diplomatic": "embassy"},
    "fire_department": {"amenity": "fire_station"},
    "library": {"amenity": "library"},
    "police_department": {"amenity": "police"},
    "town_hall": {"amenity": "townhall"},
    "religious_organization": {"amenity": "place_of_worship"},
    "church_cathedral": {"amenity": "place_of_worship", "religion": "christian"},
    "catholic_church": {
        "amenity": "place_of_worship",
        "religion": "christian",
        "denomination": "catholic",
    },
    "mosque": {"amenity": "place_of_worship", "religion": "muslim"},
    "property_management": {"office": "property_management"},
    "real_estate_agent": {"office": "estate_agent"},
    "airport": {"aeroway": "aerodrome"},
    "airport_terminal": {"aeroway": "terminal"},
    "travel_agents": {"shop": "travel_agency"},
    "train_station": {"railway": "station", "public_transport": "station"},
    "bus_station": {"amenity": "bus_station", "public_transport": "station"},
    "car_sharing": {"amenity": "car_sharing"},
    "motorcycle_parking": {"amenity": "motorcycle_parking"},
    "parking": {"amenity": "parking"},
    "car_rental_agency": {"amenity": "car_rental"},
    "home_service": {"craft": "yes"},
    "carpenter": {"craft": "carpenter"},
    "electrician": {"craft": "electrician"},
    "plasterer": {"craft": "plasterer"},
    "landscaping": {"craft": "gardener"},
    "professional_services": {"craft": "yes"},
    "lawyer": {"office": "lawyer"},
    "caterer": {"craft": "caterer"},
    "photographer": {"craft": "photographer"},
    "dry_cleaning": {"shop": "laundry", "dry_cleaning": "yes"},
    "laundromat": {"shop": "laundry"},
    "advertising_agency": {"office": "advertising_agency"},
    "architect": {"office": "architect"},
    "shoe_repair": {"shop": "shoe_repair"},
    "structure_and_geography": {"place": "yes"},
    "bridge": {"man_made": "bridge"},
    "canal": {"waterway": "canal"},
    "dam": {"waterway": "dam"},
    "island": {"place": "island"},
    "mountain": {"natural": "peak"},
    "nature_reserve": {"leisure": "nature_reserve"},
    "pier": {"man_made": "pier"},
    "quay": {"man_made": "quay"},
    "river": {"waterway": "river"},
    "weir": {"waterway": "weir"},
}
