tags = {
    "eat_and_drink": {"amenity": "restaurant"},
    "restaurant": {"amenity": "restaurant"},
    "afghan_restaurant": {"amenity": "restaurant", "cuisine": "afghan"},
    "african_restaurant": {"amenity": "restaurant", "cuisine": "african"},
    "ethiopian_restaurant": {"amenity": "restaurant", "cuisine": "ethiopian"},
    "senegalese_restaurant": {"amenity": "restaurant", "cuisine": "senegalese"},
    "south_african_restaurant": {"amenity": "restaurant"},
    "moroccan_restaurant": {"amenity": "restaurant", "cuisine": "moroccan"},
    "nigerian_restaurant": {"amenity": "restaurant"},
    "american_restaurant": {"amenity": "restaurant", "cuisine": "american"},
    "arabian_restaurant": {"amenity": "restaurant", "cuisine": "arab"},
    "belgian_restaurant": {"amenity": "restaurant", "cuisine": "belgian"},
    "latin_american_restaurant": {"amenity": "restaurant", "cuisine": "latin_american"},
    "argentine_restaurant": {"amenity": "restaurant", "cuisine": "argentinian"},
    "belizean_restaurant": {"amenity": "restaurant"},
    "bolivian_restaurant": {"amenity": "restaurant", "cuisine": "bolivian"},
    "brazilian_restaurant": {"amenity": "restaurant", "cuisine": "brazilian"},
    "chilean_restaurant": {"amenity": "restaurant"},
    "colombian_restaurant": {"amenity": "restaurant", "cuisine": "colombian"},
    "costa_rican_restaurant": {"amenity": "restaurant"},
    "cuban_restaurant": {"amenity": "restaurant", "cuisine": "cuban"},
    "ecuadorian_restaurant": {"amenity": "restaurant"},
    "guatemalan_restaurant": {"amenity": "restaurant"},
    "honduran_restaurant": {"amenity": "restaurant"},
    "mexican_restaurant": {"amenity": "restaurant", "cuisine": "mexican"},
    "nicaraguan_restaurant": {"amenity": "restaurant"},
    "panamanian_restaurant": {"amenity": "restaurant"},
    "paraguayan_restaurant": {"amenity": "restaurant"},
    "peruvian_restaurant": {"amenity": "restaurant", "cuisine": "peruvian"},
    "puerto_rican_restaurant": {"amenity": "restaurant"},
    "salvadoran_restaurant": {"amenity": "restaurant"},
    "texmex_restaurant": {"amenity": "restaurant", "cuisine": "tex-mex"},
    "uruguayan_restaurant": {"amenity": "restaurant"},
    "venezuelan_restaurant": {"amenity": "restaurant", "cuisine": "venezuelan"},
    "middle_eastern_restaurant": {"amenity": "restaurant", "cuisine": "middle_eastern"},
    "armenian_restaurant": {"amenity": "restaurant", "cuisine": "armenian"},
    "azerbaijani_restaurant": {"amenity": "restaurant"},
    "egyptian_restaurant": {"amenity": "restaurant", "cuisine": "egyptian"},
    "georgian_restaurant": {"amenity": "restaurant", "cuisine": "georgian"},
    "kofta_restaurant": {"amenity": "restaurant"},
    "kurdish_restaurant": {"amenity": "restaurant"},
    "lebanese_restaurant": {"amenity": "restaurant", "cuisine": "lebanese"},
    "persian_iranian_restaurant": {"amenity": "restaurant", "cuisine": "persian"},
    "syrian_restaurant": {"amenity": "restaurant", "cuisine": "syrian"},
    "turkish_restaurant": {"amenity": "restaurant", "cuisine": "turkish"},
    "asian_restaurant": {"amenity": "restaurant", "cuisine": "asian"},
    "asian_fusion_restaurant": {"amenity": "restaurant", "cuisine": "fusion"},
    "pan_asian_restaurant": {"amenity": "restaurant"},
    "burmese_restaurant": {"amenity": "restaurant"},
    "cambodian_restaurant": {"amenity": "restaurant", "cuisine": "cambodian"},
    "chinese_restaurant": {"amenity": "restaurant", "cuisine": "chinese"},
    "dim_sum_restaurant": {"amenity": "restaurant"},
    "filipino_restaurant": {"amenity": "restaurant", "cuisine": "filipino"},
    "indo_chinese_restaurant": {"amenity": "restaurant"},
    "indonesian_restaurant": {"amenity": "restaurant", "cuisine": "indonesian"},
    "japanese_restaurant": {"amenity": "restaurant", "cuisine": "japanese"},
    "korean_restaurant": {"amenity": "restaurant", "cuisine": "korean"},
    "sushi_restaurant": {"amenity": "restaurant", "cuisine": "sushi"},
    "laotian_restaurant": {"amenity": "restaurant"},
    "malaysian_restaurant": {"amenity": "restaurant", "cuisine": "malaysian"},
    "mongolian_restaurant": {"amenity": "restaurant", "cuisine": "mongolian"},
    "noodles_restaurant": {"amenity": "restaurant", "cuisine": "noodle"},
    "singaporean_restaurant": {"amenity": "restaurant", "cuisine": "singaporean"},
    "taiwanese_restaurant": {"amenity": "restaurant", "cuisine": "taiwanese"},
    "thai_restaurant": {"amenity": "restaurant", "cuisine": "thai"},
    "vietnamese_restaurant": {"amenity": "restaurant", "cuisine": "vietnamese"},
    "australian_restaurant": {"amenity": "restaurant", "cuisine": "australian"},
    "austrian_restaurant": {"amenity": "restaurant", "cuisine": "austrian"},
    "bangladeshi_restaurant": {"amenity": "restaurant", "cuisine": "bangladeshi"},
    "indian_restaurant": {"amenity": "restaurant", "cuisine": "indian"},
    "basque_restaurant": {"amenity": "restaurant", "cuisine": "basque"},
    "british_restaurant": {"amenity": "restaurant", "cuisine": "british"},
    "eastern_european_restaurant": {
        "amenity": "restaurant",
        "cuisine": "middle_eastern",
    },
    "belarusian_restaurant": {"amenity": "restaurant"},
    "bulgarian_restaurant": {"amenity": "restaurant", "cuisine": "bulgarian"},
    "romanian_restaurant": {"amenity": "restaurant", "cuisine": "romanian"},
    "tatar_restaurant": {"amenity": "restaurant"},
    "ukrainian_restaurant": {"amenity": "restaurant", "cuisine": "ukrainian"},
    "french_restaurant": {"amenity": "restaurant", "cuisine": "french"},
    "cajun_creole_restaurant": {"amenity": "restaurant", "cuisine": "cajun"},
    "canadian_restaurant": {"amenity": "restaurant"},
    "caribbean_restaurant": {"amenity": "restaurant", "cuisine": "caribbean"},
    "dominican_restaurant": {"amenity": "restaurant"},
    "haitian_restaurant": {"amenity": "restaurant"},
    "jamaican_restaurant": {"amenity": "restaurant", "cuisine": "jamaican"},
    "trinidadian_restaurant": {"amenity": "restaurant"},
    "german_restaurant": {"amenity": "restaurant", "cuisine": "german"},
    "catalan_restaurant": {"amenity": "restaurant"},
    "italian_restaurant": {"amenity": "restaurant", "cuisine": "italian"},
    "czech_restaurant": {"amenity": "restaurant", "cuisine": "czech"},
    "mediterranean_restaurant": {"amenity": "restaurant", "cuisine": "mediterranean"},
    "greek_restaurant": {"amenity": "restaurant", "cuisine": "greek"},
    "guamanian_restaurant": {"amenity": "restaurant"},
    "hawaiian_restaurant": {"amenity": "restaurant", "cuisine": "hawaiian"},
    "himalayan_nepalese_restaurant": {"amenity": "restaurant"},
    "hungarian_restaurant": {"amenity": "restaurant", "cuisine": "hungarian"},
    "iberian_restaurant": {"amenity": "restaurant"},
    "irish_restaurant": {"amenity": "restaurant"},
    "jewish_restaurant": {"amenity": "restaurant"},
    "international_restaurant": {"amenity": "restaurant"},
    "european_restaurant": {"amenity": "restaurant"},
    "oriental_restaurant": {"amenity": "restaurant"},
    "pakistani_restaurant": {"amenity": "restaurant"},
    "polish_restaurant": {"amenity": "restaurant"},
    "polynesian_restaurant": {"amenity": "restaurant"},
    "portuguese_restaurant": {"amenity": "restaurant"},
    "russian_restaurant": {"amenity": "restaurant"},
    "scandinavian_restaurant": {"amenity": "restaurant"},
    "danish_restaurant": {"amenity": "restaurant"},
    "norwegian_restaurant": {"amenity": "restaurant"},
    "scottish_restaurant": {"amenity": "restaurant"},
    "seafood_restaurant": {"amenity": "restaurant", "cuisine": "seafood"},
    "serbo_croation_restaurant": {"amenity": "restaurant"},
    "slovakian_restaurant": {"amenity": "restaurant"},
    "southern_restaurant": {"amenity": "restaurant"},
    "spanish_restaurant": {"amenity": "restaurant"},
    "sri_lankan_restaurant": {"amenity": "restaurant"},
    "swiss_restaurant": {"amenity": "restaurant"},
    "uzbek_restaurant": {"amenity": "restaurant"},
    "molecular_gastronomy_restaurant": {"amenity": "restaurant"},
    "haute_cuisine_restaurant": {"amenity": "restaurant"},
    "buffet_restaurant": {"amenity": "restaurant"},
    "barbecue_restaurant": {"amenity": "restaurant"},
    "burger_restaurant": {"amenity": "restaurant", "cuisine": "burger"},
    "cafetaria": {"amenity": "fast_food", "fast_food": "cafeteria"},
    "cheesesteak_restaurant": {"amenity": "restaurant"},
    "chicken_restaurant": {"amenity": "restaurant"},
    "chicken_wings_restaurant": {"amenity": "restaurant"},
    "dog_meat_restaurant": {"amenity": "restaurant"},
    "dumpling_restaurant": {"amenity": "restaurant"},
    "fast_food_restaurant": {"amenity": "fast_food"},
    "fishchbroetchen_restaurant": {"amenity": "restaurant"},
    "fish_restaurant": {"amenity": "restaurant"},
    "fish_and_chips_restaurant": {"amenity": "restaurant"},
    "fondue_restaurant": {"amenity": "restaurant"},
    "gluten_free_restaurant": {"amenity": "restaurant"},
    "baozi_restaurant": {"amenity": "restaurant"},
    "halal_restaurant": {"amenity": "restaurant"},
    "health_food_restaurant": {"amenity": "restaurant"},
    "kosher_restaurant": {"amenity": "restaurant"},
    "comfort_food_restaurant": {"amenity": "restaurant"},
    "meat_restaurant": {"amenity": "restaurant"},
    "curry_sausage_restaurant": {"amenity": "restaurant"},
    "food_court": {"amenity": "food_court"},
    "pizza_restaurant": {"amenity": "restaurant", "cuisine": "pizza"},
    "vegan_restaurant": {"amenity": "restaurant", "diet:vegan": "yes"},
    "vegetarian_restaurant": {"amenity": "restaurant", "diet:vegetarian": "yes"},
    "steakhouse": {"amenity": "restaurant", "cuisine": "steak_house"},
    "bar": {"amenity": "bar"},
    "beer_garden": {"amenity": "biergarten"},
    "bubble_tea": {"amenity": "cafe", "cuisine": "bubble_tea"},
    "pub": {"amenity": "pub"},
    "cafe": {"amenity": "cafe"},
    "coffee_shop": {"amenity": "cafe", "cuisine": "coffee_shop"},
    "accommodation": {"tourism": "yes"},
    "bed_and_breakfast": {"tourism": "guest_house", "guest_house": "bed_and_breakfast"},
    "cabin": {"tourism": "chalet"},
    "campground": {"tourism": "camp_site"},
    "cottage": {"tourism": "chalet"},
    "guest_house": {"tourism": "guest_house"},
    "hostel": {"tourism": "hostel"},
    "hotel": {"tourism": "hotel"},
    "motel": {"tourism": "motel"},
    "resort": {"leisure": "resort"},
    "beach_resort": {"leisure": "beach_resort"},
    "rv_park": {"tourism": "caravan_site"},
    "service_apartments": {"tourism": "apartment"},
    "automotive_dealer": {"shop": "car"},
    "car_dealer": {"shop": "car"},
    "motorcycle_dealer": {"shop": "motorcycle"},
    "used_car_dealer": {"shop": "car", "second_hand": "only"},
    "car_wash": {"amenity": "car_wash"},
    "motorcycle_repair": {"shop": "motorcycle_repair"},
    "tire_dealer_and_repair": {"shop": "tyres"},
    "automotive_parts_and_accessories": {"shop": "car_parts"},
    "gas_station": {"amenity": "fuel"},
    "truck_gas_station": {"amenity": "fuel", "hgv": "yes"},
    "ev_charging_station": {"amenity": "charging_station"},
    "automotive_repair": {"shop": "car_repair"},
    "bookmakers": {"shop": "bookmaker"},
    "carousel": {"attraction": "carousel"},
    "casino": {"amenity": "casino"},
    "internet_cafe": {"amenity": "internet_cafe"},
    "paintball": {"leisure": "pitch", "sport": "paintball"},
    "planetarium": {"amenity": "planetarium"},
    "baseball_stadium": {"leisure": "pitch", "sport": "baseball"},
    "basketball_stadium": {"leisure": "pitch", "sport": "basketball"},
    "cricket_ground": {"leisure": "pitch", "sport": "cricket"},
    "football_stadium": {"leisure": "pitch", "sport": "american_football"},
    "soccer_stadium": {"leisure": "pitch", "sport": "soccer"},
    "tennis_stadium": {"leisure": "pitch", "sport": "tennis"},
    "theatre": {"amenity": "theatre"},
    "water_park": {"leisure": "water_park"},
    "cinema": {"amenity": "cinema"},
    "psychic": {"shop": "psychic"},
    "amusement_park": {"tourism": "theme_park"},
    "aquarium": {"tourism": "aquarium"},
    "art_gallery": {"tourism": "gallery"},
    "beach": {"natural": "beach"},
    "botanical_garden": {"leisure": "garden", "garden:type": "botanical"},
    "castle": {"historic": "castle"},
    "fort": {"historic": "fort"},
    "fountain": {"amenity": "fountain"},
    "lake": {"natural": "water", "water": "lake"},
    "lighthouse": {"man_made": "lighthouse"},
    "marina": {"leisure": "marina"},
    "monument": {"historic": "monument"},
    "observatory": {"man_made": "observatory"},
    "palace": {"historic": "castle", "castle_type": "palace"},
    "plaza": {"place": "square"},
    "ruin": {"historic": "ruins"},
    "waterfall": {"waterway": "waterfall"},
    "zoo": {"tourism": "zoo"},
    "petting_zoo": {"tourism": "zoo", "zoo": "petting_zoo"},
    "museum": {"tourism": "museum"},
    "park": {"leisure": "park"},
    "dog_park": {"leisure": "dog_park"},
    "archery_range": {"leisure": "pitch", "sport": "archery"},
    "bowling_alley": {"leisure": "bowling_alley"},
    "disc_golf_course": {"leisure": "disc_golf_course"},
    "golf_course": {"leisure": "golf_course"},
    "driving_range": {"golf": "driving_range"},
    "gym": {"leisure": "fitness_centre"},
    "horse_riding": {"leisure": "horse_riding"},
    "miniature_golf_course": {"leisure": "miniature_golf"},
    "playground": {"leisure": "playground"},
    "swimming_pool": {"leisure": "swimming_pool"},
    "trampoline_park": {"leisure": "trampoline_park"},
    "beauty_salon": {"shop": "beauty"},
    "barber": {"shop": "hairdresser"},
    "massage": {"shop": "massage"},
    "tattoo_and_piercing": {"shop": "tattoo", "piercing": "yes"},
    "piercing": {"shop": "tattoo", "piercing": "yes"},
    "tattoo": {"shop": "tattoo"},
    "college_university": {"amenity": "university"},
    "school": {"amenity": "school"},
    "elementary_school": {"amenity": "school"},
    "high_school": {"amenity": "school"},
    "driving_school": {"amenity": "driving_school"},
    "language_school": {"amenity": "language_school"},
    "music_school": {"amenity": "music_school"},
    "financial_service": {"office": "financial"},
    "accountant": {"office": "accountant"},
    "atms": {"amenity": "atm"},
    "bank_credit_union": {"amenity": "bank"},
    "banks": {"amenity": "bank"},
    "insurance_agency": {"office": "insurance"},
    "private_establishments_and_corporates": {"office": "company"},
    "retail": {"shop": "yes"},
    "bakery": {"shop": "bakery"},
    "ice_cream_shop": {"amenity": "ice_cream"},
    "liquor_store": {"shop": "alcohol"},
    "winery": {"craft": "winery"},
    "butcher_shop": {"shop": "butcher"},
    "carpet_store": {"shop": "carpet"},
    "distillery": {"craft": "distillery"},
    "pharmacy": {"amenity": "pharmacy"},
    "bookstore": {"shop": "books"},
    "clothing_store": {"shop": "clothes"},
    "men's_clothing_store": {"shop": "clothes", "clothes": "men"},
    "women's_clothing_store": {"shop": "clothes", "clothes": "women"},
    "fashion_accessories_store": {"shop": "fashion_accessories"},
    "shoe_store": {"shop": "shoes"},
    "eyewear_and_optician": {"shop": "optician"},
    "flowers_and_gifts_shop": {"shop": "flowers"},
    "florist": {"shop": "florist"},
    "grocery_store": {"shop": "convenience"},
    "hardware_store": {"shop": "hardware"},
    "furniture_store": {"shop": "furniture"},
    "home_improvement_store": {"shop": "diy"},
    "medical_supply": {"shop": "medical_supply"},
    "hearing_aids": {"shop": "hearing_aids"},
    "pet_store": {"shop": "pet"},
    "computer_store": {"shop": "computer"},
    "convenience_store": {"shop": "convenience"},
    "department_store": {"shop": "department_store"},
    "discount_store": {"shop": "discount"},
    "electronics": {"shop": "electronics"},
    "jewelry_store": {"shop": "jewelry"},
    "mobile_phone_store": {"shop": "mobile_phone"},
    "shopping_center": {"shop": "mall"},
    "supermarket": {"shop": "supermarket"},
    "superstore": {"shop": "supermarket"},
    "bicycle_shop": {"shop": "bicycle"},
    "health_and_medical": {"healthcare": "yes"},
    "psychotherapist": {"healthcare": "psychotherapist"},
    "dentist": {"amenity": "dentist"},
    "doctor": {"amenity": "doctor"},
    "audiologist": {"healthcare": "audiologist"},
    "fertility": {
        "amenity": "clinic",
        "healthcare": "clinic",
        "healthcare:speciality": "fertility",
    },
    "podiatrist": {"healthcare": "podiatrist"},
    "acupuncture": {
        "healthcare": "alternative",
        "healthcare:speciality": "acupuncture",
    },
    "ayurveda": {"healthcare": "alternative", "healthcare:speciality": "ayurveda"},
    "halotherapy": {"healthcare:speciality": "halotherapy"},
    "hospice": {"healthcare": "hospice"},
    "hospital": {"amenity": "hospital"},
    "midwife": {"healthcare": "midwife"},
    "optometrist": {"healthcare": "optometrist"},
    "podiatry": {"amenity": "doctors", "healthcare:speciality": "podiatry"},
    "sauna": {"leisure": "sauna"},
    "speech_therapist": {"healthcare": "speech_therapist"},
    "psychiatrist": {"amenity": "doctors", "healthcare:speciality": "psychiatry"},
    "traditional_chinese_medicine": {
        "healthcare": "alternative",
        "healthcare:speciality": "traditional_chinese_medicine",
    },
    "pet_groomer": {"shop": "pet_grooming"},
    "animal_shelter": {"amenity": "animal_shelter"},
    "veterinarian": {"amenity": "veterinary"},
    "business_to_business": {"office": "yes"},
    "research_institute": {"amenity": "research_institute"},
    "coworking_space": {"amenity": "coworking_space"},
    "public_service_and_government": {"office": "yes"},
    "charity_organization": {"office": "charity"},
    "homeless_shelter": {
        "amenity": "social_facility",
        "social_facility": "shelter",
        "social_facility:for": "homeless",
    },
    "post_office": {"amenity": "post_office"},
    "community_center": {"amenity": "community_centre"},
    "courthouse": {"amenity": "courthouse"},
    "embassy": {"office": "diplomatic", "diplomatic": "embassy"},
    "fire_department": {"amenity": "fire_station"},
    "library": {"amenity": "library"},
    "police_department": {"amenity": "police"},
    "town_hall": {"amenity": "townhall"},
    "religious_organization": {"amenity": "place_of_worship"},
    "church_cathedral": {"amenity": "place_of_worship", "religion": "christian"},
    "catholic_church": {
        "amenity": "place_of_worship",
        "religion": "christian",
        "denomination": "catholic",
    },
    "mosque": {"amenity": "place_of_worship", "religion": "muslim"},
    "property_management": {"office": "property_management"},
    "real_estate_agent": {"office": "estate_agent"},
    "airport": {"aeroway": "aerodrome"},
    "airport_terminal": {"aeroway": "terminal"},
    "travel_agents": {"shop": "travel_agency"},
    "train_station": {"railway": "station", "public_transport": "station"},
    "bus_station": {"amenity": "bus_station", "public_transport": "station"},
    "car_sharing": {"amenity": "car_sharing"},
    "motorcycle_parking": {"amenity": "motorcycle_parking"},
    "parking": {"amenity": "parking"},
    "car_rental_agency": {"amenity": "car_rental"},
    "home_service": {"craft": "yes"},
    "carpenter": {"craft": "carpenter"},
    "electrician": {"craft": "electrician"},
    "plasterer": {"craft": "plasterer"},
    "landscaping": {"craft": "gardener"},
    "professional_services": {"craft": "yes"},
    "lawyer": {"office": "lawyer"},
    "caterer": {"craft": "caterer"},
    "photographer": {"craft": "photographer"},
    "dry_cleaning": {"shop": "laundry", "dry_cleaning": "yes"},
    "laundromat": {"shop": "laundry"},
    "advertising_agency": {"office": "advertising_agency"},
    "architect": {"office": "architect"},
    "shoe_repair": {"shop": "shoe_repair"},
    "structure_and_geography": {"place": "yes"},
    "bridge": {"man_made": "bridge"},
    "canal": {"waterway": "canal"},
    "dam": {"waterway": "dam"},
    "island": {"place": "island"},
    "mountain": {"natural": "peak"},
    "nature_reserve": {"leisure": "nature_reserve"},
    "pier": {"man_made": "pier"},
    "quay": {"man_made": "quay"},
    "river": {"waterway": "river"},
    "weir": {"waterway": "weir"},
}


unfilled = {
    "eat_and_drink": {"amenity": "restaurant"},
    "restaurant": {"amenity": "restaurant"},
    "afghan_restaurant": {"amenity": "restaurant", "cuisine": "afghan"},
    "african_restaurant": {"amenity": "restaurant", "cuisine": "african"},
    "ethiopian_restaurant": {"amenity": "restaurant", "cuisine": "ethiopian"},
    "senegalese_restaurant": {"amenity": "restaurant", "cuisine": "senegalese"},
    "south_african_restaurant": {"amenity": "restaurant"},
    "moroccan_restaurant": {"amenity": "restaurant", "cuisine": "moroccan"},
    "nigerian_restaurant": {"amenity": "restaurant"},
    "american_restaurant": {"amenity": "restaurant", "cuisine": "american"},
    "arabian_restaurant": {"amenity": "restaurant", "cuisine": "arab"},
    "belgian_restaurant": {"amenity": "restaurant", "cuisine": "belgian"},
    "latin_american_restaurant": {"amenity": "restaurant", "cuisine": "latin_american"},
    "argentine_restaurant": {"amenity": "restaurant", "cuisine": "argentinian"},
    "belizean_restaurant": {"amenity": "restaurant"},
    "bolivian_restaurant": {"amenity": "restaurant", "cuisine": "bolivian"},
    "brazilian_restaurant": {"amenity": "restaurant", "cuisine": "brazilian"},
    "chilean_restaurant": {"amenity": "restaurant"},
    "colombian_restaurant": {"amenity": "restaurant", "cuisine": "colombian"},
    "costa_rican_restaurant": {"amenity": "restaurant"},
    "cuban_restaurant": {"amenity": "restaurant", "cuisine": "cuban"},
    "ecuadorian_restaurant": {"amenity": "restaurant"},
    "guatemalan_restaurant": {"amenity": "restaurant"},
    "honduran_restaurant": {"amenity": "restaurant"},
    "mexican_restaurant": {"amenity": "restaurant", "cuisine": "mexican"},
    "nicaraguan_restaurant": {"amenity": "restaurant"},
    "panamanian_restaurant": {"amenity": "restaurant"},
    "paraguayan_restaurant": {"amenity": "restaurant"},
    "peruvian_restaurant": {"amenity": "restaurant", "cuisine": "peruvian"},
    "puerto_rican_restaurant": {"amenity": "restaurant"},
    "salvadoran_restaurant": {"amenity": "restaurant"},
    "texmex_restaurant": {"amenity": "restaurant", "cuisine": "tex-mex"},
    "uruguayan_restaurant": {"amenity": "restaurant"},
    "venezuelan_restaurant": {"amenity": "restaurant", "cuisine": "venezuelan"},
    "middle_eastern_restaurant": {"amenity": "restaurant", "cuisine": "middle_eastern"},
    "armenian_restaurant": {"amenity": "restaurant", "cuisine": "armenian"},
    "azerbaijani_restaurant": {"amenity": "restaurant"},
    "egyptian_restaurant": {"amenity": "restaurant", "cuisine": "egyptian"},
    "georgian_restaurant": {"amenity": "restaurant", "cuisine": "georgian"},
    "israeli_restaurant": {},
    "kofta_restaurant": {"amenity": "restaurant"},
    "kurdish_restaurant": {"amenity": "restaurant"},
    "lebanese_restaurant": {"amenity": "restaurant", "cuisine": "lebanese"},
    "persian_iranian_restaurant": {"amenity": "restaurant", "cuisine": "persian"},
    "syrian_restaurant": {"amenity": "restaurant", "cuisine": "syrian"},
    "turkish_restaurant": {"amenity": "restaurant", "cuisine": "turkish"},
    "asian_restaurant": {"amenity": "restaurant", "cuisine": "asian"},
    "asian_fusion_restaurant": {"amenity": "restaurant", "cuisine": "fusion"},
    "pan_asian_restaurant": {"amenity": "restaurant"},
    "burmese_restaurant": {"amenity": "restaurant"},
    "cambodian_restaurant": {"amenity": "restaurant", "cuisine": "cambodian"},
    "chinese_restaurant": {"amenity": "restaurant", "cuisine": "chinese"},
    "dim_sum_restaurant": {"amenity": "restaurant"},
    "filipino_restaurant": {"amenity": "restaurant", "cuisine": "filipino"},
    "indo_chinese_restaurant": {"amenity": "restaurant"},
    "indonesian_restaurant": {"amenity": "restaurant", "cuisine": "indonesian"},
    "japanese_restaurant": {"amenity": "restaurant", "cuisine": "japanese"},
    "korean_restaurant": {"amenity": "restaurant", "cuisine": "korean"},
    "sushi_restaurant": {"amenity": "restaurant", "cuisine": "sushi"},
    "laotian_restaurant": {"amenity": "restaurant"},
    "malaysian_restaurant": {"amenity": "restaurant", "cuisine": "malaysian"},
    "mongolian_restaurant": {"amenity": "restaurant", "cuisine": "mongolian"},
    "noodles_restaurant": {"amenity": "restaurant", "cuisine": "noodle"},
    "singaporean_restaurant": {"amenity": "restaurant", "cuisine": "singaporean"},
    "taiwanese_restaurant": {"amenity": "restaurant", "cuisine": "taiwanese"},
    "thai_restaurant": {"amenity": "restaurant", "cuisine": "thai"},
    "vietnamese_restaurant": {"amenity": "restaurant", "cuisine": "vietnamese"},
    "hong_kong_style_cafe": {},
    "australian_restaurant": {"amenity": "restaurant", "cuisine": "australian"},
    "austrian_restaurant": {"amenity": "restaurant", "cuisine": "austrian"},
    "bangladeshi_restaurant": {"amenity": "restaurant", "cuisine": "bangladeshi"},
    "indian_restaurant": {"amenity": "restaurant", "cuisine": "indian"},
    "basque_restaurant": {"amenity": "restaurant", "cuisine": "basque"},
    "british_restaurant": {"amenity": "restaurant", "cuisine": "british"},
    "eastern_european_restaurant": {
        "amenity": "restaurant",
        "cuisine": "middle_eastern",
    },
    "belarusian_restaurant": {"amenity": "restaurant"},
    "bulgarian_restaurant": {"amenity": "restaurant", "cuisine": "bulgarian"},
    "romanian_restaurant": {"amenity": "restaurant", "cuisine": "romanian"},
    "tatar_restaurant": {"amenity": "restaurant"},
    "ukrainian_restaurant": {"amenity": "restaurant", "cuisine": "ukrainian"},
    "french_restaurant": {"amenity": "restaurant", "cuisine": "french"},
    "cajun_creole_restaurant": {"amenity": "restaurant", "cuisine": "cajun"},
    "canadian_restaurant": {"amenity": "restaurant"},
    "caribbean_restaurant": {"amenity": "restaurant", "cuisine": "caribbean"},
    "dominican_restaurant": {"amenity": "restaurant"},
    "haitian_restaurant": {"amenity": "restaurant"},
    "jamaican_restaurant": {"amenity": "restaurant", "cuisine": "jamaican"},
    "trinidadian_restaurant": {"amenity": "restaurant"},
    "german_restaurant": {"amenity": "restaurant", "cuisine": "german"},
    "catalan_restaurant": {"amenity": "restaurant"},
    "italian_restaurant": {"amenity": "restaurant", "cuisine": "italian"},
    "czech_restaurant": {"amenity": "restaurant", "cuisine": "czech"},
    "mediterranean_restaurant": {"amenity": "restaurant", "cuisine": "mediterranean"},
    "greek_restaurant": {"amenity": "restaurant", "cuisine": "greek"},
    "guamanian_restaurant": {"amenity": "restaurant"},
    "hawaiian_restaurant": {"amenity": "restaurant", "cuisine": "hawaiian"},
    "himalayan_nepalese_restaurant": {"amenity": "restaurant"},
    "hungarian_restaurant": {"amenity": "restaurant", "cuisine": "hungarian"},
    "iberian_restaurant": {"amenity": "restaurant"},
    "irish_restaurant": {"amenity": "restaurant"},
    "jewish_restaurant": {"amenity": "restaurant"},
    "international_restaurant": {"amenity": "restaurant"},
    "european_restaurant": {"amenity": "restaurant"},
    "oriental_restaurant": {"amenity": "restaurant"},
    "pakistani_restaurant": {"amenity": "restaurant"},
    "polish_restaurant": {"amenity": "restaurant"},
    "polynesian_restaurant": {"amenity": "restaurant"},
    "portuguese_restaurant": {"amenity": "restaurant"},
    "russian_restaurant": {"amenity": "restaurant"},
    "scandinavian_restaurant": {"amenity": "restaurant"},
    "danish_restaurant": {"amenity": "restaurant"},
    "norwegian_restaurant": {"amenity": "restaurant"},
    "scottish_restaurant": {"amenity": "restaurant"},
    "seafood_restaurant": {"amenity": "restaurant", "cuisine": "seafood"},
    "serbo_croation_restaurant": {"amenity": "restaurant"},
    "slovakian_restaurant": {"amenity": "restaurant"},
    "southern_restaurant": {"amenity": "restaurant"},
    "spanish_restaurant": {"amenity": "restaurant"},
    "sri_lankan_restaurant": {"amenity": "restaurant"},
    "swiss_restaurant": {"amenity": "restaurant"},
    "uzbek_restaurant": {"amenity": "restaurant"},
    "molecular_gastronomy_restaurant": {"amenity": "restaurant"},
    "haute_cuisine_restaurant": {"amenity": "restaurant"},
    "salad_bar": {},
    "brasserie": {},
    "buffet_restaurant": {"amenity": "restaurant"},
    "barbecue_restaurant": {"amenity": "restaurant"},
    "burger_restaurant": {"amenity": "restaurant", "cuisine": "burger"},
    "canteen": {},
    "cafeteria": {},
    "cheesesteak_restaurant": {"amenity": "restaurant"},
    "chicken_restaurant": {"amenity": "restaurant"},
    "chicken_wings_restaurant": {"amenity": "restaurant"},
    "dog_meat_restaurant": {"amenity": "restaurant"},
    "dumpling_restaurant": {"amenity": "restaurant"},
    "fast_food_restaurant": {"amenity": "fast_food"},
    "fishchbroetchen_restaurant": {"amenity": "restaurant"},
    "acai_bowls": {},
    "fish_restaurant": {"amenity": "restaurant"},
    "fish_and_chips_restaurant": {"amenity": "restaurant"},
    "fondue_restaurant": {"amenity": "restaurant"},
    "gluten_free_restaurant": {"amenity": "restaurant"},
    "baozi_restaurant": {"amenity": "restaurant"},
    "halal_restaurant": {"amenity": "restaurant"},
    "bistro": {},
    "health_food_restaurant": {"amenity": "restaurant"},
    "kosher_restaurant": {"amenity": "restaurant"},
    "comfort_food_restaurant": {"amenity": "restaurant"},
    "meat_restaurant": {"amenity": "restaurant"},
    "curry_sausage_restaurant": {"amenity": "restaurant"},
    "diner": {},
    "diy_foods_restaurant": {},
    "doner_kebab": {},
    "empanadas": {},
    "nasi_restaurant": {},
    "flatbread_restaurant": {},
    "food_court": {"amenity": "food_court"},
    "gastropub": {},
    "pizza_restaurant": {"amenity": "restaurant", "cuisine": "pizza"},
    "pop_up_restaurant": {},
    "poutinerie_restaurant": {},
    "vegan_restaurant": {"amenity": "restaurant", "diet:vegan": "yes"},
    "vegetarian_restaurant": {"amenity": "restaurant", "diet:vegetarian": "yes"},
    "wok_restaurant": {},
    "wrap_restaurant": {},
    "piadina_restaurant": {},
    "poke": {},
    "pigs_trotters_restaurant": {},
    "potato_restaurant": {},
    "rotisserie_chicken_restaurant": {},
    "schnitzel_restaurant": {},
    "soul_food": {},
    "steakhouse": {"amenity": "restaurant", "cuisine": "steak_house"},
    "supper_club": {},
    "tapas_bar": {"amenity": "restaurant"},
    "venison_restaurant": {},
    "wild_game_meats_restaurant": {"amenity": "restaurant"},
    "falafel_restaurant": {},
    "taco_restaurant": {},
    "hot_dog_restaurant": {},
    "live_and_raw_food_restaurant": {},
    "soup_restaurant": {},
    "theme_restaurant": {},
    "bar_and_grill_restaurant": {},
    "meatball_restaurant": {},
    "waffle_restaurant": {},
    "breakfast_and_brunch_restaurant": {},
    "pancake_house": {},
    "bagel_restaurant": {},
    "baguettes": {},
    "bar": {"amenity": "bar"},
    "airport_lounge": {},
    "beach_bar": {"amenity": "bar"},
    "beer_bar": {"amenity": "bar"},
    "beer_garden": {"amenity": "biergarten"},
    "brewery": {"craft": "brewery"},
    "bubble_tea": {"amenity": "cafe", "cuisine": "bubble_tea"},
    "champagne_bar": {},
    "cidery": {},
    "cigar_bar": {},
    "cocktail_bar": {"amenity": "bar"},
    "dive_bar": {"amenity": "bar"},
    "drive_thru_bar": {"amenity": "bar", "drive_through": "yes"},
    "gay_bar": {"amenity": "bar", "lgbtq": "primary"},
    "hookah_bar": {"amenity": "bar"},
    "hotel_bar": {"amenity": "bar"},
    "irish_pub": {"amenity": "bar", "cuisine": "irish"},
    "kombucha": {},
    "lounge": {},
    "milk_bar": {},
    "milkshake_bar": {},
    "pub": {"amenity": "pub"},
    "sake_bar": {"amenity": "bar"},
    "speakeasy": {"amenity": "bar"},
    "sports_bar": {"amenity": "bar"},
    "sugar_shack": {},
    "tabac": {},
    "tiki_bar": {"amenity": "bar"},
    "vermouth_bar": {"amenity": "bar"},
    "whiskey_bar": {"amenity": "bar"},
    "wine_bar": {"amenity": "bar"},
    "smoothie_juice_bar": {},
    "piano_bar": {"amenity": "bar", "live_music": "yes"},
    "cafe": {"amenity": "cafe"},
    "coffee_roastery": {"shop": "coffee"},
    "tea_room": {"amenity": "cafe"},
    "coffee_shop": {"amenity": "cafe", "cuisine": "coffee_shop"},
    "accommodation": {"tourism": "yes"},
    "bed_and_breakfast": {"tourism": "guest_house", "guest_house": "bed_and_breakfast"},
    "cabin": {"tourism": "chalet"},
    "campground": {"tourism": "camp_site"},
    "cottage": {"tourism": "chalet"},
    "guest_house": {"tourism": "guest_house"},
    "health_retreats": {},
    "holiday_rental_home": {},
    "hostel": {"tourism": "hostel"},
    "hotel": {"tourism": "hotel"},
    "inn": {},
    "lodge": {},
    "motel": {"tourism": "motel"},
    "mountain_huts": {},
    "resort": {"leisure": "resort"},
    "beach_resort": {"leisure": "beach_resort"},
    "rv_park": {"tourism": "caravan_site"},
    "service_apartments": {"tourism": "apartment"},
    "automotive": {},
    "automotive_dealer": {"shop": "car"},
    "car_buyer": {},
    "car_dealer": {"shop": "car"},
    "commercial_vehicle_dealer": {},
    "golf_cart_dealer": {},
    "motorcycle_dealer": {"shop": "motorcycle"},
    "motorsport_vehicle_dealer": {},
    "recreational_vehicle_dealer": {},
    "scooter_dealers": {},
    "trailer_dealer": {},
    "truck_dealer": {},
    "used_car_dealer": {"shop": "car", "second_hand": "only"},
    "automotive_services_and_repair": {},
    "auto_body_shop": {},
    "auto_customization": {},
    "auto_detailing": {},
    "auto_electrical_repair": {},
    "auto_glass_service": {},
    "car_window_tinting": {},
    "auto_restoration_services": {},
    "auto_security": {},
    "automobile_registration_service": {},
    "automotive_consultant": {},
    "automotive_storage_facility": {},
    "brake_service_and_repair": {},
    "car_inspector": {},
    "car_stereo_installation": {},
    "car_wash": {"amenity": "car_wash"},
    "diy_auto_shop": {},
    "emissions_inspection": {},
    "engine_repair_service": {},
    "exhaust_and_muffler_repair": {},
    "hybrid_car_repair": {},
    "motorcycle_repair": {"shop": "motorcycle_repair"},
    "motorsport_vehicle_repair": {},
    "oil_change_station": {},
    "recreation_vehicle_repair": {},
    "roadside_assistance": {},
    "emergency_roadside_service": {},
    "mobile_dent_repair": {},
    "tire_dealer_and_repair": {"shop": "tyres"},
    "transmission_repair": {},
    "towing_service": {},
    "trailer_repair": {},
    "truck_repair": {},
    "auto_upholstery": {},
    "vehicle_wrap": {},
    "vehicle_shipping": {},
    "wheel_and_rim_repair": {},
    "automotive_wheel_polishing_service": {},
    "windshield_installation_and_repair": {},
    "automotive_parts_and_accessories": {"shop": "car_parts"},
    "recreational_vehicle_parts_and_accessories": {},
    "car_stereo_store": {},
    "motorcycle_gear": {},
    "motorsports_store": {},
    "interlock_system": {},
    "aircraft_dealer": {},
    "aircraft_repair": {},
    "aircraft_parts_and_supplies": {},
    "avionics_shop": {},
    "boat_dealer": {},
    "boat_service_and_repair": {},
    "boat_parts_and_accessories": {},
    "gas_station": {"amenity": "fuel"},
    "truck_gas_station": {"amenity": "fuel", "hgv": "yes"},
    "fuel_dock": {},
    "ev_charging_station": {"amenity": "charging_station"},
    "truck_stop": {},
    "automobile_leasing": {},
    "automotive_repair": {"shop": "car_repair"},
    "auto_company": {},
    "motorcycle_manufacturer": {},
    "arts_and_entertainment": {},
    "adult_entertainment": {},
    "erotic_massage": {},
    "strip_club": {},
    "striptease_dancer": {},
    "arcade": {},
    "auditorium": {},
    "bar_crawl": {},
    "betting_center": {},
    "bingo_hall": {},
    "bookmakers": {"shop": "bookmaker"},
    "cabaret": {},
    "carousel": {"attraction": "carousel"},
    "casino": {"amenity": "casino"},
    "chamber_of_handicraft": {},
    "choir": {},
    "circus": {},
    "club_crawl": {},
    "comedy_club": {},
    "topic_concert_venue": {"amenity": "music_venue"},
    "country_club": {},
    "country_dance_hall": {},
    "dance_club": {},
    "dinner_theater": {},
    "eatertainment": {},
    "escape_rooms": {},
    "exhibition_and_trade_center": {},
    "glass_blowing": {},
    "indoor_playcenter": {},
    "internet_cafe": {"amenity": "internet_cafe"},
    "jazz_and_blues": {},
    "karaoke": {},
    "laser_tag": {},
    "makerspace": {},
    "marching_band": {},
    "music_venue": {},
    "musical_band_orchestras_and_symphonies": {},
    "opera_and_ballet": {},
    "paint_and_sip": {},
    "paintball": {"leisure": "pitch", "sport": "paintball"},
    "performing_arts": {},
    "planetarium": {"amenity": "planetarium"},
    "rodeo": {},
    "salsa_club": {},
    "wildlife_sanctuary": {},
    "stadium_arena": {},
    "baseball_stadium": {"leisure": "pitch", "sport": "baseball"},
    "basketball_stadium": {"leisure": "pitch", "sport": "basketball"},
    "cricket_ground": {"leisure": "pitch", "sport": "cricket"},
    "football_stadium": {"leisure": "pitch", "sport": "american_football"},
    "hockey_arena": {},
    "rugby_stadium": {},
    "soccer_stadium": {"leisure": "pitch", "sport": "soccer"},
    "tennis_stadium": {"leisure": "pitch", "sport": "tennis"},
    "track_stadium": {},
    "studio_taping": {},
    "theaters_and_performance_venues": {},
    "theatre": {"amenity": "theatre"},
    "ticket_sales": {},
    "virtual_reality_center": {},
    "water_park": {"leisure": "water_park"},
    "cinema": {"amenity": "cinema"},
    "drive_in_theater": {},
    "outdoor_movies": {},
    "farm": {},
    "attraction_farm": {},
    "orchard": {},
    "pick_your_own_farm": {},
    "poultry_farm": {},
    "ranch": {},
    "festival": {},
    "fair": {},
    "film_festivals_and_organizations": {},
    "general_festivals": {},
    "holiday_market": {},
    "music_festivals_and_organizations": {},
    "trade_fair": {},
    "social_club": {},
    "fraternal_organization": {},
    "veterans_organization": {},
    "supernatural_reading": {},
    "astrologer": {},
    "mystic": {},
    "psychic": {"shop": "psychic"},
    "psychic_medium": {},
    "attractions_and_activities": {},
    "amusement_park": {"tourism": "theme_park"},
    "aquarium": {"tourism": "aquarium"},
    "architecture": {},
    "art_gallery": {"tourism": "gallery"},
    "atv_rentals_and_tours": {},
    "axe_throwing": {},
    "backpacking_area": {},
    "beach": {"natural": "beach"},
    "beach_combing_area": {},
    "boat_rental_and_training": {},
    "boating_places": {},
    "bobsledding_field": {},
    "botanical_garden": {"leisure": "garden", "garden:type": "botanical"},
    "bungee_jumping_center": {},
    "canyon": {},
    "castle": {"historic": "castle"},
    "cave": {},
    "challenge_courses_center": {},
    "cliff_jumping_center": {},
    "climbing_service": {},
    "crater": {},
    "cultural_center": {},
    "fishing_charter": {},
    "flyboarding_rental": {},
    "fort": {"historic": "fort"},
    "fountain": {"amenity": "fountain"},
    "go_kart_track": {},
    "haunted_house": {},
    "high_gliding_center": {},
    "horseback_riding_service": {},
    "hot_air_balloons_tour": {},
    "hot_springs": {},
    "jet_skis_rental": {},
    "kiteboarding_instruction": {},
    "lake": {"natural": "water", "water": "lake"},
    "landmark_and_historical_building": {},
    "lighthouse": {"man_made": "lighthouse"},
    "lookout": {},
    "marina": {"leisure": "marina"},
    "monument": {"historic": "monument"},
    "mountain_bike_parks": {},
    "observatory": {"man_made": "observatory"},
    "paddleboard_rental": {},
    "palace": {"historic": "castle", "castle_type": "palace"},
    "parasailing_ride_service": {},
    "plaza": {"place": "square"},
    "rafting_kayaking_area": {},
    "rock_climbing_spot": {},
    "ruin": {"historic": "ruins"},
    "sailing_area": {},
    "sand_dune": {},
    "scavenger_hunts_provider": {},
    "sculpture_statue": {},
    "ski_area": {},
    "skyline": {},
    "sledding_rental": {},
    "snorkeling_equipment_rental": {},
    "snorkeling": {},
    "snowboarding_center": {},
    "stargazing_area": {},
    "street_art": {},
    "trail": {},
    "hiking_trail": {},
    "mountain_bike_trails": {},
    "waterfall": {"waterway": "waterfall"},
    "surfing": {},
    "surfboard_rental": {},
    "windsurfing_center": {},
    "ziplining_center": {},
    "zoo": {"tourism": "zoo"},
    "petting_zoo": {"tourism": "zoo", "zoo": "petting_zoo"},
    "museum": {"tourism": "museum"},
    "art_museum": {},
    "asian_art_museum": {},
    "cartooning_museum": {},
    "contemporary_art_museum": {},
    "children's_museum": {},
    "costume_museum": {},
    "decorative_arts_museum": {},
    "design_museum": {},
    "modern_art_museum": {},
    "photography_museum": {},
    "textile_museum": {},
    "history_museum": {},
    "civilization_museum": {},
    "community_museum": {},
    "military_museum": {},
    "national_museum": {},
    "science_museum": {},
    "computer_museum": {},
    "state_museum": {},
    "aviation_museum": {},
    "sports_museum": {},
    "park": {"leisure": "park"},
    "dog_park": {"leisure": "dog_park"},
    "memorial_park": {},
    "national_park": {},
    "state_park": {},
    "active_life": {},
    "sports_and_recreation_venue": {},
    "adventure_sports_center": {},
    "american_football_field": {},
    "airsoft_fields": {},
    "archery_range": {"leisure": "pitch", "sport": "archery"},
    "atv_recreation_park": {},
    "badminton_court": {},
    "baseball_field": {},
    "basketball_court": {},
    "batting_cage": {},
    "beach_volleyball_court": {},
    "bicycle_path": {},
    "bocce_ball_court": {},
    "bowling_alley": {"leisure": "bowling_alley"},
    "bubble_soccer_field": {},
    "disc_golf_course": {"leisure": "disc_golf_course"},
    "flyboarding_center": {},
    "futsal_field": {},
    "golf_course": {"leisure": "golf_course"},
    "driving_range": {"golf": "driving_range"},
    "gym": {"leisure": "fitness_centre"},
    "gymnastics_center": {},
    "handball_court": {},
    "hockey_field": {},
    "horse_riding": {"leisure": "horse_riding"},
    "equestrian_facility": {},
    "horse_racing_track": {},
    "skate_park": {},
    "skating_rink": {},
    "ice_skating_rink": {},
    "roller_skating_rink": {},
    "hang_gliding_center": {},
    "kiteboarding": {},
    "miniature_golf_course": {"leisure": "miniature_golf"},
    "paddleboarding_center": {},
    "playground": {"leisure": "playground"},
    "pool_billiards": {},
    "pool_hall": {},
    "racquetball_court": {},
    "rock_climbing_gym": {},
    "rugby_pitch": {},
    "shooting_range": {},
    "sky_diving": {},
    "soccer_field": {},
    "squash_court": {},
    "swimming_pool": {"leisure": "swimming_pool"},
    "tennis_court": {},
    "trampoline_park": {"leisure": "trampoline_park"},
    "tubing_provider": {},
    "volleyball_court": {},
    "wildlife_hunting_range": {},
    "zorbing_center": {},
    "diving_center": {},
    "free_diving_center": {},
    "scuba_diving_center": {},
    "race_track": {},
    "sports_and_fitness_instruction": {},
    "climbing_class": {},
    "cycling_classes": {},
    "golf_instructor": {},
    "paddleboarding_lessons": {},
    "racing_experience": {},
    "rock_climbing_instructor": {},
    "free_diving_instruction": {},
    "scuba_diving_instruction": {},
    "aerial_fitness_center": {},
    "barre_classes": {},
    "boot_camp": {},
    "boxing_class": {},
    "boxing_club": {},
    "boxing_gym": {},
    "cardio_classes": {},
    "dance_school": {},
    "ems_training": {},
    "fitness_trainer": {},
    "health_consultant": {},
    "meditation_center": {},
    "pilates_studio": {},
    "qi_gong_studio": {},
    "self_defense_classes": {},
    "ski_and_snowboard_school": {},
    "surfing_school": {},
    "swimming_instructor": {},
    "tai_chi_studio": {},
    "yoga_instructor": {},
    "yoga_studio": {},
    "sports_club_and_league": {},
    "amateur_sports_league": {},
    "amateur_sports_team": {},
    "beach_volleyball_club": {},
    "esports_league": {},
    "esports_team": {},
    "fencing_club": {},
    "fishing_club": {},
    "football_club": {},
    "go_kart_club": {},
    "gymnastics_club": {},
    "lawn_bowling_club": {},
    "nudist_clubs": {},
    "paddle_tennis_club": {},
    "professional_sports_league": {},
    "professional_sports_team": {},
    "rowing_club": {},
    "sailing_club": {},
    "school_sports_league": {},
    "school_sports_team": {},
    "soccer_club": {},
    "surf_lifesaving_club": {},
    "table_tennis_club": {},
    "volleyball_club": {},
    "golf_club": {},
    "indoor_golf_center": {},
    "martial_arts_club": {},
    "brazilian_jiu_jitsu_club": {},
    "chinese_martial_arts_club": {},
    "karate_club": {},
    "kickboxing_club": {},
    "muay_thai_club": {},
    "taekwondo_club": {},
    "sports_and_recreation_rental_and_services": {},
    "beach_equipment_rentals": {},
    "bike_rentals": {},
    "canoe_and_kayak_hire_service": {},
    "scooter_rental": {},
    "sport_equipment_rentals": {},
    "beauty_and_spa": {},
    "aromatherapy": {},
    "beauty_salon": {"shop": "beauty"},
    "acne_treatment": {},
    "barber": {"shop": "hairdresser"},
    "eyebrow_service": {},
    "eyelash_service": {},
    "foot_care": {},
    "hair_extensions": {},
    "hair_loss_center": {},
    "hair_replacement": {},
    "health_spa": {},
    "makeup_artist": {},
    "massage": {"shop": "massage"},
    "nail_salon": {},
    "onsen": {},
    "permanent_makeup": {},
    "tattoo_and_piercing": {"shop": "tattoo", "piercing": "yes"},
    "piercing": {"shop": "tattoo", "piercing": "yes"},
    "tattoo": {"shop": "tattoo"},
    "public_bath_houses": {},
    "teeth_whitening": {},
    "turkish_baths": {},
    "hair_removal": {},
    "laser_hair_removal": {},
    "sugaring": {},
    "threading_service": {},
    "waxing": {},
    "hair_salon": {},
    "blow_dry_blow_out_service": {},
    "hair_stylist": {},
    "kids_hair_salon": {},
    "spas": {},
    "medical_spa": {},
    "day_spa": {},
    "skin_care": {},
    "esthetician": {},
    "tanning_salon": {},
    "spray_tanning": {},
    "tanning_bed": {},
    "image_consultant": {},
    "education": {},
    "adult_education": {},
    "board_of_education_offices": {},
    "campus_building": {},
    "college_counseling": {},
    "college_university": {"amenity": "university"},
    "architecture_schools": {},
    "business_schools": {},
    "engineering_schools": {},
    "law_schools": {},
    "medical_sciences_schools": {},
    "dentistry_schools": {},
    "pharmacy_schools": {},
    "veterinary_schools": {},
    "science_schools": {},
    "educational_research_institute": {},
    "educational_services": {},
    "archaeological_services": {},
    "educational_camp": {},
    "private_tutor": {},
    "school": {"amenity": "school"},
    "charter_school": {},
    "elementary_school": {"amenity": "school"},
    "high_school": {"amenity": "school"},
    "middle_school": {},
    "montessori_school": {},
    "preschool": {},
    "private_school": {},
    "public_school": {},
    "religious_school": {},
    "waldorf_school": {},
    "school_district_offices": {},
    "specialty_school": {},
    "art_school": {},
    "bartending_school": {},
    "cheerleading": {},
    "childbirth_education": {},
    "circus_school": {},
    "computer_coaching": {},
    "cooking_school": {},
    "cosmetology_school": {},
    "cpr_classes": {},
    "drama_school": {},
    "driving_school": {"amenity": "driving_school"},
    "dui_school": {},
    "firearm_training": {},
    "first_aid_class": {},
    "flight_school": {},
    "food_safety_training": {},
    "language_school": {"amenity": "language_school"},
    "massage_school": {},
    "medical_school": {},
    "music_school": {"amenity": "music_school"},
    "nursing_school": {},
    "parenting_classes": {},
    "photography_classes": {},
    "speech_training": {},
    "sports_school": {},
    "traffic_school": {},
    "vocational_and_technical_school": {},
    "student_union": {},
    "tasting_classes": {},
    "cheese_tasting_classes": {},
    "wine_tasting_classes": {},
    "test_preparation": {},
    "tutoring_center": {},
    "civil_examinations_academy": {},
    "financial_service": {"office": "financial"},
    "accountant": {"office": "accountant"},
    "atms": {"amenity": "atm"},
    "bank_credit_union": {"amenity": "bank"},
    "banks": {"amenity": "bank"},
    "credit_union": {},
    "brokers": {},
    "business_brokers": {},
    "stock_and_bond_brokers": {},
    "business_banking_service": {},
    "business_financing": {},
    "check_cashing_payday_loans": {},
    "coin_dealers": {},
    "collection_agencies": {},
    "credit_and_debt_counseling": {},
    "currency_exchange": {},
    "debt_relief_services": {},
    "financial_advising": {},
    "holding_companies": {},
    "investment_management_company": {},
    "installment_loans": {},
    "mortgage_lender": {},
    "auto_loan_provider": {},
    "insurance_agency": {"office": "insurance"},
    "auto_insurance": {},
    "farm_insurance": {},
    "fidelity_and_surety_bonds": {},
    "home_and_rental_insurance": {},
    "life_insurance": {},
    "investing": {},
    "money_transfer_services": {},
    "tax_services": {},
    "trusts": {},
    "private_establishments_and_corporates": {"office": "company"},
    "corporate_entertainment_services": {},
    "corporate_gift_supplier": {},
    "corporate_office": {},
    "private_equity_firm": {},
    "retail": {"shop": "yes"},
    "food": {},
    "back_shop": {},
    "bagel_shop": {},
    "bakery": {"shop": "bakery"},
    "flatbread": {},
    "beer_wine_and_spirits": {},
    "box_lunch_supplier": {},
    "patisserie_cake_shop": {},
    "chimney_cake_shop": {},
    "cupcake_shop": {},
    "custom_cakes_shop": {},
    "coffee_and_tea_supplies": {},
    "csa_farm": {},
    "desserts": {},
    "donuts": {},
    "fishmonger": {},
    "food_delivery_service": {},
    "food_stand": {},
    "food_truck": {},
    "friterie": {},
    "health_food_store": {},
    "ice_cream_and_frozen_yoghurt": {},
    "gelato": {},
    "ice_cream_shop": {"amenity": "ice_cream"},
    "frozen_yoghurt_shop": {},
    "shaved_ice_shop": {},
    "shaved_snow_shop": {},
    "imported_food": {},
    "kiosk": {},
    "liquor_store": {"shop": "alcohol"},
    "mulled_wine": {},
    "pie_shop": {},
    "pretzels": {},
    "sandwich_shop": {},
    "smokehouse": {},
    "street_vendor": {},
    "pizza_delivery_service": {},
    "specialty_foods": {},
    "delicatessen": {},
    "frozen_foods": {},
    "indian_sweets_shop": {},
    "macarons": {},
    "pasta_shop": {},
    "winery": {"craft": "winery"},
    "wine_tasting_room": {},
    "auto_parts_and_supply_store": {},
    "beverage_store": {},
    "boat_parts_and_supply_store": {},
    "butcher_shop": {"shop": "butcher"},
    "candy_store": {},
    "japanese_confectionery_shop": {},
    "carpet_store": {"shop": "carpet"},
    "cheese_shop": {},
    "chocolatier": {},
    "distillery": {"craft": "distillery"},
    "drugstore": {},
    "flooring_store": {},
    "fruits_and_vegetables": {},
    "health_market": {},
    "hearing_aid_provider": {},
    "herb_and_spice_shop": {},
    "honey_farm_shop": {},
    "meat_shop": {},
    "olive_oil": {},
    "party_supply": {},
    "pharmacy": {"amenity": "pharmacy"},
    "popcorn_shop": {},
    "seafood_market": {},
    "water_store": {},
    "shopping": {},
    "arts_and_crafts": {},
    "art_supply_store": {},
    "atelier": {},
    "cooking_classes": {},
    "costume_store": {},
    "craft_shop": {},
    "embroidery_and_crochet": {},
    "fabric_store": {},
    "framing_store": {},
    "handicraft_shop": {},
    "paint_your_own_pottery": {},
    "books_mags_music_and_video": {},
    "bookstore": {"shop": "books"},
    "academic_bookstore": {},
    "comic_books_store": {},
    "music_and_dvd_store": {},
    "newspaper_and_magazines_store": {},
    "video_and_video_game_rentals": {},
    "video_game_store": {},
    "vinyl_record_store": {},
    "building_supply_store": {},
    "lumber_store": {},
    "fashion": {},
    "clothing_store": {"shop": "clothes"},
    "ceremonial_clothing": {},
    "children's_clothing_store": {},
    "clothing_rental": {},
    "denim_wear_store": {},
    "designer_clothing": {},
    "formal_wear_store": {},
    "fur_clothing": {},
    "lingerie_store": {},
    "maternity_wear": {},
    "men's_clothing_store": {"shop": "clothes", "clothes": "men"},
    "t_shirt_store": {},
    "custom_t_shirt_store": {},
    "traditional_clothing": {},
    "women's_clothing_store": {"shop": "clothes", "clothes": "women"},
    "fashion_accessories_store": {"shop": "fashion_accessories"},
    "hat_shop": {},
    "leather_goods": {},
    "plus_size_clothing": {},
    "saree_shop": {},
    "sleepwear": {},
    "stocking": {},
    "used_vintage_and_consignment": {},
    "handbag_stores": {},
    "shoe_store": {"shop": "shoes"},
    "orthopedic_shoe_store": {},
    "cosmetic_and_beauty_supplies": {},
    "hair_supply_stores": {},
    "eyewear_and_optician": {"shop": "optician"},
    "sunglasses_store": {},
    "farming_equipment_store": {},
    "forklift_dealer": {},
    "flowers_and_gifts_shop": {"shop": "flowers"},
    "florist": {"shop": "florist"},
    "gift_shop": {},
    "grocery_store": {"shop": "convenience"},
    "specialty_grocery_store": {},
    "asian_grocery_store": {},
    "dairy_stores": {},
    "ethical_grocery": {},
    "indian_grocery_store": {},
    "japanese_grocery_store": {},
    "korean_grocery_store": {},
    "kosher_grocery_store": {},
    "mexican_grocery_store": {},
    "organic_grocery_store": {},
    "rice_shop": {},
    "russian_grocery_store": {},
    "home_and_garden": {},
    "hardware_store": {"shop": "hardware"},
    "welding_supply_store": {},
    "appliance_store": {},
    "bedding_and_bath_stores": {},
    "candle_store": {},
    "christmas_trees": {},
    "electrical_supply_store": {},
    "furniture_accessory_store": {},
    "furniture_store": {"shop": "furniture"},
    "grilling_equipment": {},
    "holiday_decor": {},
    "home_decor": {},
    "home_goods_store": {},
    "home_improvement_store": {"shop": "diy"},
    "hot_tubs_and_pools": {},
    "lawn_mower_store": {},
    "lighting_store": {},
    "linen": {},
    "mattress_store": {},
    "nursery_and_gardening": {},
    "outdoor_furniture_store": {},
    "paint_store": {},
    "playground_equipment_supplier": {},
    "pumpkin_patch": {},
    "rug_store": {},
    "tableware_supplier": {},
    "tile_store": {},
    "wallpaper_store": {},
    "window_treatment_store": {},
    "woodworking_supply_store": {},
    "kitchen_and_bath": {},
    "bathroom_fixture_stores": {},
    "kitchen_supply_store": {},
    "hydroponic_gardening": {},
    "medical_supply": {"shop": "medical_supply"},
    "dental_supply_store": {},
    "hearing_aids": {"shop": "hearing_aids"},
    "pet_store": {"shop": "pet"},
    "bird_shop": {},
    "aquatic_pet_store": {},
    "reptile_shop": {},
    "adult_store": {},
    "agricultural_seed_store": {},
    "antique_store": {},
    "army_and_navy_store": {},
    "auction_house": {},
    "car_auction": {},
    "baby_gear_and_furniture": {},
    "battery_store": {},
    "bazaars": {},
    "boutique": {},
    "brewing_supply_store": {},
    "bridal_shop": {},
    "cannabis_dispensary": {},
    "cards_and_stationery_store": {},
    "computer_store": {"shop": "computer"},
    "concept_shop": {},
    "convenience_store": {"shop": "convenience"},
    "custom_clothing": {},
    "customized_merchandise": {},
    "department_store": {"shop": "department_store"},
    "discount_store": {"shop": "discount"},
    "do_it_yourself_store": {},
    "drone_store": {},
    "duty_free_shop": {},
    "educational_supply_store": {},
    "electronics": {"shop": "electronics"},
    "farmers_market": {},
    "firework_retailer": {},
    "fitness_exercise_equipment": {},
    "flea_market": {},
    "flower_markets": {},
    "gemstone_and_mineral": {},
    "gold_buyer": {},
    "guitar_store": {},
    "gun_and_ammo": {},
    "herbal_shop": {},
    "audio_visual_equipment_store": {},
    "hobby_shop": {},
    "home_theater_systems_stores": {},
    "horse_equipment_shop": {},
    "international_grocery_store": {},
    "jewelry_store": {"shop": "jewelry"},
    "knitting_supply": {},
    "livestock_feed_and_supply_store": {},
    "luggage_store": {},
    "market_stall": {},
    "military_surplus_store": {},
    "mobile_phone_accessories": {},
    "mobile_phone_store": {"shop": "mobile_phone"},
    "musical_instrument_store": {},
    "night_market": {},
    "office_equipment": {},
    "online_shop": {},
    "outlet_store": {},
    "packing_supply": {},
    "pawn_shop": {},
    "pen_store": {},
    "perfume_store": {},
    "personal_shopper": {},
    "photography_store_and_services": {},
    "piano_store": {},
    "pool_and_billiards": {},
    "pop_up_shop": {},
    "props": {},
    "public_market": {},
    "religious_items": {},
    "rental_kiosks": {},
    "safe_store": {},
    "safety_equipment": {},
    "shopping_center": {"shop": "mall"},
    "shopping_passage": {},
    "souvenir_shop": {},
    "spiritual_shop": {},
    "supermarket": {"shop": "supermarket"},
    "superstore": {"shop": "supermarket"},
    "tabletop_games": {},
    "thrift_store": {},
    "tobacco_shop": {},
    "toy_store": {},
    "trophy_shop": {},
    "uniform_store": {},
    "used_bookstore": {},
    "e_cigarette_store": {},
    "vitamins_and_supplements": {},
    "watch_store": {},
    "wholesale_store": {},
    "wig_store": {},
    "sporting_goods": {},
    "archery_shop": {},
    "bicycle_shop": {"shop": "bicycle"},
    "dive_shop": {},
    "golf_equipment": {},
    "hockey_equipment": {},
    "hunting_and_fishing_supplies": {},
    "outdoor_gear": {},
    "skate_shop": {},
    "ski_and_snowboard_shop": {},
    "sports_wear": {},
    "dance_wear": {},
    "surf_shop": {},
    "swimwear_store": {},
    "tire_shop": {},
    "tire_repair_shop": {},
    "health_and_medical": {"healthcare": "yes"},
    "abuse_and_addiction_treatment": {},
    "alcohol_and_drug_treatment_centers": {},
    "crisis_intervention_services": {},
    "eating_disorder_treatment_centers": {},
    "counseling_and_mental_health": {},
    "family_counselor": {},
    "marriage_or_relationship_counselor": {},
    "psychoanalyst": {},
    "psychologist": {},
    "psychotherapist": {"healthcare": "psychotherapist"},
    "sex_therapist": {},
    "sophrologist": {},
    "sports_psychologist": {},
    "stress_management_services": {},
    "suicide_prevention_services": {},
    "dental_hygienist": {},
    "mobile_clinic": {},
    "storefront_clinic": {},
    "dentist": {"amenity": "dentist"},
    "cosmetic_dentist": {},
    "endodontist": {},
    "general_dentistry": {},
    "oral_surgeon": {},
    "orthodontist": {},
    "pediatric_dentist": {},
    "periodontist": {},
    "diagnostic_services": {},
    "diagnostic_imaging": {},
    "laboratory_testing": {},
    "doctor": {"amenity": "doctor"},
    "allergist": {},
    "anesthesiologist": {},
    "audiologist": {"healthcare": "audiologist"},
    "cardiologist": {},
    "cosmetic_surgeon": {},
    "dermatologist": {},
    "ear_nose_and_throat": {},
    "emergency_medicine": {},
    "endocrinologist": {},
    "endoscopist": {},
    "family_practice": {},
    "fertility": {
        "amenity": "clinic",
        "healthcare": "clinic",
        "healthcare:speciality": "fertility",
    },
    "gastroenterologist": {},
    "geneticist": {},
    "gerontologist": {},
    "hepatologist": {},
    "homeopathic_medicine": {},
    "hospitalist": {},
    "immunodermatologist": {},
    "infectious_disease_specialist": {},
    "naturopathic_holistic": {},
    "nephrologist": {},
    "neurologist": {},
    "neurotologist": {},
    "neuropathologist": {},
    "obstetrician_and_gynecologist": {},
    "oncologist": {},
    "orthopedist": {},
    "osteopathic_physician": {},
    "otologist": {},
    "pain_management": {},
    "pathologist": {},
    "phlebologist": {},
    "physician_assistant": {},
    "plastic_surgeon": {},
    "podiatrist": {"healthcare": "podiatrist"},
    "preventive_medicine": {},
    "proctologist": {},
    "pulmonologist": {},
    "radiologist": {},
    "rheumatologist": {},
    "spine_surgeon": {},
    "sports_medicine": {},
    "tattoo_removal": {},
    "toxicologist": {},
    "tropical_medicine": {},
    "undersea_hyperbaric_medicine": {},
    "urologist": {},
    "vascular_medicine": {},
    "geriatric_medicine": {},
    "geriatric_psychiatry": {},
    "abortion_clinic": {},
    "acupuncture": {
        "healthcare": "alternative",
        "healthcare:speciality": "acupuncture",
    },
    "aesthetician": {},
    "alcohol_and_drug_treatment_center": {},
    "alternative_medicine": {},
    "ambulance_and_ems_services": {},
    "animal_assisted_therapy": {},
    "assisted_living_facility": {},
    "ayurveda": {"healthcare": "alternative", "healthcare:speciality": "ayurveda"},
    "behavior_analyst": {},
    "blood_and_plasma_donation_center": {},
    "body_contouring": {},
    "cancer_treatment_center": {},
    "cannabis_clinic": {},
    "cannabis_collective": {},
    "childrens_hospital": {},
    "chiropractor": {},
    "colonics": {},
    "community_health_center": {},
    "concierge_medicine": {},
    "cryotherapy": {},
    "dialysis_clinic": {},
    "dietitian": {},
    "doula": {},
    "emergency_room": {},
    "environmental_medicine": {},
    "eye_care_clinic": {},
    "float_spa": {},
    "halfway_house": {},
    "halotherapy": {"healthcare:speciality": "halotherapy"},
    "health_and_wellness_club": {},
    "health_coach": {},
    "health_department": {},
    "health_insurance_office": {},
    "hospice": {"healthcare": "hospice"},
    "hospital": {"amenity": "hospital"},
    "hydrotherapy": {},
    "hypnosis_hypnotherapy": {},
    "iv_hydration": {},
    "lactation_services": {},
    "laser_eye_surgery_lasik": {},
    "lice_treatment": {},
    "massage_therapy": {},
    "maternity_centers": {},
    "medical_cannabis_referral": {},
    "medical_service_organizations": {},
    "medical_transportation": {},
    "memory_care": {},
    "midwife": {"healthcare": "midwife"},
    "nurse_practitioner": {},
    "nutritionist": {},
    "occupational_medicine": {},
    "occupational_therapy": {},
    "optometrist": {"healthcare": "optometrist"},
    "organ_and_tissue_donor_service": {},
    "orthotics": {},
    "oxygen_bar": {},
    "paternity_tests_and_services": {},
    "physical_therapy": {},
    "placenta_encapsulation_service": {},
    "podiatry": {"amenity": "doctors", "healthcare:speciality": "podiatry"},
    "prenatal_perinatal_care": {},
    "prosthetics": {},
    "prosthodontist": {},
    "psychomotor_therapist": {},
    "public_health_clinic": {},
    "reflexology": {},
    "reiki": {},
    "sauna": {"leisure": "sauna"},
    "skilled_nursing": {},
    "sleep_specialist": {},
    "speech_therapist": {"healthcare": "speech_therapist"},
    "sperm_clinic": {},
    "surgical_center": {},
    "ultrasound_imaging_center": {},
    "urgent_care_clinic": {},
    "weight_loss_center": {},
    "wellness_program": {},
    "women's_health_clinic": {},
    "internal_medicine": {"amenity":"doctors","healthcare:speciality": "internal"},
    "hematology": {},
    "medical_center": {},
    "bulk_billing": {},
    "osteopath": {},
    "walk_in_clinic": {},
    "ophthalmologist": {},
    "retina_specialist": {},
    "pediatrician": {},
    "pediatric_anesthesiology": {},
    "pediatric_cardiology": {},
    "pediatric_endocrinology": {},
    "pediatric_gastroenterology": {},
    "pediatric_infectious_disease": {},
    "pediatric_nephrology": {},
    "pediatric_neurology": {},
    "pediatric_oncology": {},
    "pediatric_orthopedic_surgery": {},
    "pediatric_pulmonology": {},
    "pediatric_radiology": {},
    "pediatric_surgery": {},
    "personal_care_service": {},
    "home_health_care": {},
    "psychiatrist": {"amenity": "doctors", "healthcare:speciality": "psychiatry"},
    "child_psychiatrist": {},
    "rehabilitation_center": {},
    "addiction_rehabilitation_center": {},
    "surgeon": {},
    "cardiovascular_and_thoracic_surgeon": {},
    "traditional_chinese_medicine": {
        "healthcare": "alternative",
        "healthcare:speciality": "traditional_chinese_medicine",
    },
    "tui_na": {},
    "pets": {},
    "pet_services": {},
    "animal_hospital": {},
    "animal_physical_therapy": {},
    "aquarium_services": {},
    "dog_walkers": {},
    "emergency_pet_hospital": {},
    "farrier_services": {},
    "holistic_animal_care": {},
    "pet_breeder": {},
    "pet_cemetery_and_crematorium_services": {},
    "pet_groomer": {"shop": "pet_grooming"},
    "pet_hospice": {},
    "pet_insurance": {},
    "pet_photography": {},
    "pet_sitting": {},
    "pet_transportation": {},
    "pet_waste_removal": {},
    "pet_boarding": {},
    "pet_training": {},
    "dog_trainer": {},
    "horse_trainer": {},
    "animal_rescue_service": {},
    "animal_shelter": {"amenity": "animal_shelter"},
    "horse_boarding": {},
    "pet_adoption": {},
    "veterinarian": {"amenity": "veterinary"},
    "business_to_business": {"office": "yes"},
    "business": {},
    "travel_company": {},
    "ferry_boat_company": {},
    "airline": {},
    "food_beverage_service_distribution": {},
    "bottled_water_company": {},
    "tobacco_company": {},
    "clothing_company": {},
    "bags_luggage_company": {},
    "hotel_supply_service": {},
    "commercial_industrial": {},
    "inventory_control_service": {},
    "industrial_company": {},
    "automation_services": {},
    "occupational_safety": {},
    "b2b_agriculture_and_food": {},
    "agricultural_service": {},
    "agricultural_cooperatives": {},
    "agriculture": {},
    "agricultural_engineering_service": {},
    "apiaries_and_beekeepers": {},
    "b2b_dairies": {},
    "b2b_food_products": {},
    "fish_farms_and_hatcheries": {},
    "fish_farm": {},
    "livestock_breeder": {},
    "livestock_dealers": {},
    "poultry_farming": {},
    "b2b_farming": {},
    "b2b_farms": {},
    "pig_farm": {},
    "dairy_farm": {},
    "urban_farm": {},
    "farming_services": {},
    "farm_equipment_and_supply": {},
    "fertilizer_store": {},
    "grain_elevators": {},
    "greenhouses": {},
    "irrigation_companies": {},
    "crops_production": {},
    "grain_production": {},
    "orchards_production": {},
    "business_manufacturing_and_supply": {},
    "mattress_manufacturing": {},
    "glass_manufacturer": {},
    "appliance_manufacturer": {},
    "aircraft_manufacturer": {},
    "b2b_autos_and_vehicles": {},
    "auto_manufacturers_and_distributors": {},
    "b2b_tires": {},
    "b2b_furniture_and_housewares": {},
    "furniture_manufacturers": {},
    "furniture_wholesalers": {},
    "b2b_machinery_and_tools": {},
    "b2b_equipment_maintenance_and_repair": {},
    "industrial_equipment": {},
    "abrasives_supplier": {},
    "aggregate_supplier": {},
    "aluminum_supplier": {},
    "b2b_apparel": {},
    "b2b_electronic_equipment": {},
    "b2b_hardware": {},
    "b2b_jewelers": {},
    "b2b_rubber_and_plastics": {},
    "plastic_company": {},
    "plastic_manufacturer": {},
    "b2b_sporting_and_recreation_goods": {},
    "b2b_textiles": {},
    "battery_inverter_supplier": {},
    "bearing_supplier": {},
    "casting_molding_and_machining": {},
    "cement_supplier": {},
    "chemical_plant": {},
    "cleaning_products_supplier": {},
    "cosmetic_products_manufacturer": {},
    "drinking_water_dispenser": {},
    "fastener_supplier": {},
    "granite_supplier": {},
    "hvac_supplier": {},
    "jewelry_and_watches_manufacturer": {},
    "jewelry_manufacturer": {},
    "leather_products_manufacturer": {},
    "lighting_fixture_manufacturers": {},
    "pipe_supplier": {},
    "plastic_fabrication_company": {},
    "plastic_injection_molding_workshop": {},
    "printing_equipment_and_supply": {},
    "retaining_wall_supplier": {},
    "sand_and_gravel_supplier": {},
    "scale_supplier": {},
    "seal_and_hanko_dealers": {},
    "shoe_factory": {},
    "spring_supplier": {},
    "stone_supplier": {},
    "turnery": {},
    "window_supplier": {},
    "metals": {},
    "metal_supplier": {},
    "metal_plating_service": {},
    "metal_fabricator": {},
    "iron_and_steel_industry": {},
    "iron_work": {},
    "scrap_metals": {},
    "sheet_metal": {},
    "steel_fabricators": {},
    "mills": {},
    "cotton_mill": {},
    "flour_mill": {},
    "paper_mill": {},
    "rice_mill": {},
    "saw_mill": {},
    "textile_mill": {},
    "weaving_mill": {},
    "wood_and_pulp": {},
    "logging_equipment_and_supplies": {},
    "logging_services": {},
    "logging_contractor": {},
    "b2b_medical_support_services": {},
    "biotechnology_company": {},
    "clinical_laboratories": {},
    "dental_laboratories": {},
    "hospital_equipment_and_supplies": {},
    "medical_research_and_development": {},
    "pharmaceutical_companies": {},
    "surgical_appliances_and_supplies": {},
    "b2b_science_and_technology": {},
    "b2b_scientific_equipment": {},
    "research_institute": {"amenity": "research_institute"},
    "scientific_laboratories": {},
    "business_advertising": {},
    "business_signage": {},
    "direct_mail_advertising": {},
    "marketing_consultant": {},
    "newspaper_advertising": {},
    "outdoor_advertising": {},
    "promotional_products_and_services": {},
    "publicity_service": {},
    "radio_and_television_commercials": {},
    "telemarketing_services": {},
    "business_equipment_and_supply": {},
    "beauty_product_supplier": {},
    "beverage_supplier": {},
    "business_office_supplies_and_stationery": {},
    "electronic_parts_supplier": {},
    "energy_equipment_and_solution": {},
    "hydraulic_equipment_supplier": {},
    "laboratory_equipment_supplier": {},
    "thread_supplier": {},
    "vending_machine_supplier": {},
    "water_softening_equipment_supplier": {},
    "wholesaler": {},
    "wholesale_grocer": {},
    "spices_wholesaler": {},
    "computer_wholesaler": {},
    "electrical_wholesaler": {},
    "fabric_wholesaler": {},
    "fitness_equipment_wholesaler": {},
    "fmcg_wholesaler": {},
    "footwear_wholesaler": {},
    "greengrocer": {},
    "industrial_spares_and_products_wholesaler": {},
    "iron_and_steel_store": {},
    "lingerie_wholesaler": {},
    "meat_wholesaler": {},
    "optical_wholesaler": {},
    "pharmaceutical_products_wholesaler": {},
    "produce_wholesaler": {},
    "seafood_wholesaler": {},
    "tea_wholesaler": {},
    "threads_and_yarns_wholesaler": {},
    "tools_wholesaler": {},
    "wholesale_florist": {},
    "wine_wholesaler": {},
    "restaurant_wholesale": {},
    "restaurant_equipment_and_supply": {},
    "business_storage_and_transportation": {},
    "motor_freight_trucking": {},
    "pipeline_transportation": {},
    "railroad_freight": {},
    "b2b_storage_and_warehouses": {},
    "warehouse_rental_services_and_yards": {},
    "warehouses": {},
    "freight_and_cargo_service": {},
    "distribution_services": {},
    "freight_forwarding_agency": {},
    "trucks_and_industrial_vehicles": {},
    "b2b_forklift_dealers": {},
    "b2b_tractor_dealers": {},
    "b2b_truck_equipment_parts_and_accessories": {},
    "truck_dealer_for_businesses": {},
    "truck_repair_and_services_for_businesses": {},
    "business_to_business_services": {},
    "agricultural_production": {},
    "audio_visual_production_and_design": {},
    "boat_builder": {},
    "business_records_storage_and_management": {},
    "coworking_space": {"amenity": "coworking_space"},
    "domestic_business_and_trade_organizations": {},
    "human_resource_services": {},
    "information_technology_company": {},
    "laser_cutting_service_provider": {},
    "telecommunications_company": {},
    "tower_communication_service": {},
    "transcription_services": {},
    "translating_and_interpreting_services": {},
    "consultant_and_general_service": {},
    "food_consultant": {},
    "business_management_services": {},
    "executive_search_consultants": {},
    "manufacturing_and_industrial_consultant": {},
    "secretarial_services": {},
    "manufacturers_agents_and_representatives": {},
    "environmental_and_ecological_services_for_businesses": {},
    "b2b_cleaning_and_waste_management": {},
    "water_treatment_equipment_and_services": {},
    "energy_management_and_conservation_consultants": {},
    "environmental_conservation_and_ecological_organizations": {},
    "environmental_renewable_natural_resource": {},
    "forestry_consultants": {},
    "geological_services": {},
    "food_and_beverage_exporter": {},
    "background_check_services": {},
    "international_business_and_trade_services": {},
    "importer_and_exporter": {},
    "exporters": {},
    "importers": {},
    "restaurant_management": {},
    "b2b_energy_mining": {},
    "mining": {},
    "coal_and_coke": {},
    "quarries": {},
    "oil_and_gas": {},
    "b2b_oil_and_gas_extraction_and_services": {},
    "oil_and_gas_exploration_and_development": {},
    "oil_and_gas_field_equipment_and_services": {},
    "oil_refiners": {},
    "power_plants_and_power_plant_service": {},
    "public_service_and_government": {"office": "yes"},
    "energy_company": {},
    "electric_utility_provider": {},
    "public_utility_company": {},
    "law_enforcement": {},
    "organization": {},
    "agriculture_association": {},
    "environmental_conservation_organization": {},
    "home_organization": {},
    "labor_union": {},
    "non_governmental_association": {},
    "political_organization": {},
    "private_association": {},
    "public_and_government_association": {},
    "social_service_organizations": {},
    "charity_organization": {"office": "charity"},
    "food_banks": {},
    "foster_care_services": {},
    "gay_and_lesbian_services_organization": {},
    "homeless_shelter": {
        "amenity": "social_facility",
        "social_facility": "shelter",
        "social_facility:for": "homeless",
    },
    "housing_authorities": {},
    "senior_citizen_services": {},
    "social_and_human_services": {},
    "social_welfare_center": {},
    "volunteer_association": {},
    "child_protection_service": {},
    "youth_organizations": {},
    "community_services_non_profits": {},
    "disability_services_and_support_organization": {},
    "government_services": {},
    "social_security_services": {},
    "jail_and_prison": {},
    "juvenile_detention_center": {},
    "post_office": {"amenity": "post_office"},
    "shipping_collection_services": {},
    "public_toilet": {},
    "armed_forces_branch": {},
    "central_government_office": {},
    "chambers_of_commerce": {},
    "children_hall": {},
    "civic_center": {},
    "community_center": {"amenity": "community_centre"},
    "courthouse": {"amenity": "courthouse"},
    "department_of_motor_vehicles": {},
    "department_of_social_service": {},
    "embassy": {"office": "diplomatic", "diplomatic": "embassy"},
    "family_service_center": {},
    "federal_government_offices": {},
    "fire_department": {"amenity": "fire_station"},
    "immigration_and_naturalization": {},
    "library": {"amenity": "library"},
    "local_and_state_government_offices": {},
    "low_income_housing": {},
    "national_security_services": {},
    "office_of_vital_records": {},
    "pension": {},
    "police_department": {"amenity": "police"},
    "political_party_office": {},
    "railway_service": {},
    "registry_office": {},
    "retirement_home": {},
    "scout_hall": {},
    "tax_office": {},
    "town_hall": {"amenity": "townhall"},
    "unemployment_office": {},
    "weather_station": {},
    "religious_organization": {"amenity": "place_of_worship"},
    "church_cathedral": {"amenity": "place_of_worship", "religion": "christian"},
    "anglican_church": {
        "amenity": "place_of_worship",
        "religion": "christian",
        "denomination": "anglican",
    },
    "baptist_church": {
        "amenity": "place_of_worship",
        "religion": "christian",
        "denomination": "baptist",
    },
    "catholic_church": {
        "amenity": "place_of_worship",
        "religion": "christian",
        "denomination": "catholic",
    },
    "episcopal_church": {
        "amenity": "place_of_worship",
        "religion": "christian",
        "denomination": "episcopal",
    },
    "evangelical_church": {
        "amenity": "place_of_worship",
        "religion": "christian",
        "denomination": "evangelical",
    },
    "jehovahs_witness_kingdom_hall": {},
    "pentecostal_church": {
        "amenity": "place_of_worship",
        "religion": "christian",
        "denomination": "pentecostal",
    },
    "mission": {},
    "buddhist_temple": {"amenity": "place_of_worship", "religion": "buddhist"},
    "convents_and_monasteries": {},
    "hindu_temple": {"amenity": "place_of_worship", "religion": "hindu"},
    "mosque": {"amenity": "place_of_worship", "religion": "muslim"},
    "religious_destination": {},
    "shinto_shrines": {},
    "sikh_temple": {},
    "synagogue": {},
    "temple": {},
    "real_estate": {},
    "real_estate_investment": {},
    "builders": {},
    "home_developer": {},
    "apartments": {"building": "apartments"},
    "art_space_rental": {},
    "commercial_real_estate": {},
    "condominium": {},
    "display_home_center": {},
    "estate_liquidation": {},
    "holiday_park": {},
    "home_staging": {},
    "homeowner_association": {},
    "housing_cooperative": {},
    "kitchen_incubator": {},
    "mobile_home_dealer": {},
    "mobile_home_park": {},
    "mortgage_broker": {},
    "property_management": {"office": "property_management"},
    "shared_office_space": {},
    "university_housing": {},
    "real_estate_agent": {"office": "estate_agent"},
    "apartment_agent": {},
    "real_estate_service": {},
    "escrow_services": {},
    "land_surveying": {},
    "real_estate_photography": {},
    "rental_services": {},
    "travel": {},
    "airport": {"aeroway": "aerodrome"},
    "airport_terminal": {"aeroway": "terminal"},
    "balloon_ports": {},
    "domestic_airports": {},
    "gliderports": {},
    "heliports": {},
    "major_airports": {},
    "seaplane_bases": {},
    "ultralight_airports": {},
    "travel_services": {},
    "passport_and_visa_services": {},
    "visa_agent": {},
    "travel_agents": {"shop": "travel_agency"},
    "sightseeing_tour_agency": {},
    "luggage_storage": {},
    "visitor_center": {},
    "road_structures_and_services": {},
    "rest_areas": {},
    "toll_stations": {},
    "tours": {},
    "aerial_tours": {},
    "architectural_tours": {},
    "art_tours": {},
    "beer_tours": {},
    "bike_tours": {},
    "boat_tours": {},
    "bus_tours": {},
    "cannabis_tour": {},
    "food_tours": {},
    "historical_tours": {},
    "scooter_tours": {},
    "walking_tours": {},
    "whale_watching_tours": {},
    "wine_tours": {},
    "transportation": {},
    "trains": {},
    "train_station": {"railway": "station", "public_transport": "station"},
    "airlines": {},
    "airport_shuttles": {},
    "bicycle_sharing_location": {},
    "bike_parking": {},
    "bike_sharing": {},
    "bus_service": {},
    "bus_station": {"amenity": "bus_station", "public_transport": "station"},
    "cable_car_service": {},
    "car_sharing": {"amenity": "car_sharing"},
    "coach_bus": {},
    "ferry_service": {},
    "light_rail_and_subway_stations": {},
    "limo_services": {},
    "metro_station": {},
    "motorcycle_parking": {"amenity": "motorcycle_parking"},
    "park_and_rides": {},
    "parking": {"amenity": "parking"},
    "pedicab_service": {},
    "private_jet_charters": {},
    "public_transportation": {},
    "ride_sharing": {},
    "taxi_rank": {},
    "taxi_service": {},
    "town_car_service": {},
    "transport_interchange": {},
    "water_taxi": {},
    "agriturismo": {},
    "airline_ticket_agency": {},
    "bus_ticket_agency": {},
    "rental_service": {},
    "car_rental_agency": {"amenity": "car_rental"},
    "motorcycle_rentals": {},
    "rv_rentals": {},
    "trailer_rentals": {},
    "truck_rentals": {},
    "country_house": {},
    "houseboat": {},
    "railway_ticket_agent": {},
    "rest_stop": {},
    "ryokan": {},
    "self_catering_accommodation": {},
    "ski_resort": {},
    "vacation_rental_agents": {},
    "mass_media": {},
    "print_media": {},
    "media_critic": {},
    "movie_critic": {},
    "music_critic": {},
    "video_game_critic": {},
    "media_news_company": {},
    "media_agency": {},
    "radio_station": {},
    "television_station": {},
    "weather_forecast_services": {},
    "animation_studio": {},
    "book_magazine_distribution": {},
    "broadcasting_media_production": {},
    "game_publisher": {},
    "movie_television_studio": {},
    "music_production": {},
    "topic_publisher": {},
    "social_media_company": {},
    "media_news_website": {},
    "media_restoration_service": {},
    "art_restoration": {},
    "theatrical_productions": {},
    "home_service": {"craft": "yes"},
    "ceiling_and_roofing_repair_and_service": {},
    "ceiling_service": {},
    "roofing": {},
    "chimney_service": {},
    "chimney_sweep": {},
    "contractor": {},
    "altering_and_remodeling_contractor": {},
    "building_contractor": {},
    "flooring_contractors": {},
    "paving_contractor": {},
    "damage_restoration": {},
    "fire_and_water_damage_restoration": {},
    "artificial_turf": {},
    "bathroom_remodeling": {},
    "bathtub_and_sink_repairs": {},
    "cabinet_sales_service": {},
    "carpenter": {"craft": "carpenter"},
    "carpet_cleaning": {},
    "carpet_installation": {},
    "childproofing": {},
    "closet_remodeling": {},
    "countertop_installation": {},
    "deck_and_railing_sales_service": {},
    "demolition_service": {},
    "door_sales_service": {},
    "drywall_services": {},
    "electrician": {"craft": "electrician"},
    "excavation_service": {},
    "exterior_design": {},
    "fence_and_gate_sales_service": {},
    "fire_protection_service": {},
    "fireplace_service": {},
    "firewood": {},
    "foundation_repair": {},
    "furniture_assembly": {},
    "garage_door_service": {},
    "glass_and_mirror_sales_service": {},
    "grout_service": {},
    "gutter_service": {},
    "handyman": {},
    "holiday_decorating": {},
    "home_automation": {},
    "home_cleaning": {},
    "home_energy_auditor": {},
    "home_inspector": {},
    "home_network_installation": {},
    "home_security": {},
    "home_window_tinting": {},
    "house_sitting": {},
    "hvac_services": {},
    "insulation_installation": {},
    "interior_design": {},
    "irrigation": {},
    "key_and_locksmith": {"shop": "locksmith"},
    "kitchen_remodeling": {},
    "lighting_fixtures_and_equipment": {},
    "masonry_concrete": {},
    "mobile_home_repair": {},
    "movers": {},
    "packing_services": {},
    "painting": {},
    "patio_covers": {},
    "plasterer": {"craft": "plasterer"},
    "pool_and_hot_tub_services": {},
    "pool_cleaning": {},
    "pressure_washing": {},
    "refinishing_services": {},
    "security_systems": {},
    "shades_and_blinds": {},
    "shutters": {},
    "siding": {},
    "solar_installation": {},
    "solar_panel_cleaning": {},
    "structural_engineer": {},
    "stucco_services": {},
    "television_service_providers": {},
    "tiling": {},
    "wallpaper_installers": {},
    "washer_and_dryer_repair_service": {},
    "water_heater_installation_repair": {},
    "water_purification_services": {},
    "waterproofing": {},
    "window_washing": {},
    "landscaping": {"craft": "gardener"},
    "gardener": {},
    "landscape_architect": {},
    "lawn_service": {},
    "tree_services": {},
    "plumbing": {},
    "backflow_services": {},
    "windows_installation": {},
    "skylight_installation": {},
    "professional_services": {"craft": "yes"},
    "cleaning_services": {},
    "industrial_cleaning_services": {},
    "janitorial_services": {},
    "office_cleaning": {},
    "construction_services": {},
    "blueprinters": {},
    "construction_management": {},
    "inspection_services": {},
    "road_contractor": {},
    "wind_energy": {},
    "engineering_services": {},
    "civil_engineers": {},
    "instrumentation_engineers": {},
    "mechanical_engineers": {},
    "metal_materials_and_experts": {},
    "blacksmiths": {},
    "ironworkers": {},
    "welders": {},
    "stone_and_masonry": {},
    "gravel_professionals": {},
    "lime_professionals": {},
    "marble_and_granite_professionals": {},
    "masonry_contractors": {},
    "lawyer": {"office": "lawyer"},
    "estate_planning_law": {},
    "wills_trusts_and_probate": {},
    "appellate_practice_lawyers": {},
    "bankruptcy_law": {},
    "business_law": {},
    "civil_rights_lawyers": {},
    "contract_law": {},
    "criminal_defense_law": {},
    "disability_law": {},
    "divorce_and_family_law": {},
    "dui_law": {},
    "employment_law": {},
    "entertainment_law": {},
    "general_litigation": {},
    "immigration_law": {},
    "ip_and_internet_law": {},
    "medical_law": {},
    "paralegal_services": {},
    "personal_injury_law": {},
    "real_estate_law": {},
    "social_security_law": {},
    "tax_law": {},
    "traffic_ticketing_law": {},
    "workers_compensation_law": {},
    "event_planning": {},
    "balloon_services": {},
    "bartender": {},
    "boat_charter": {},
    "caricature": {},
    "caterer": {"craft": "caterer"},
    "clown": {},
    "dj_service": {},
    "event_technology_service": {},
    "face_painting": {},
    "floral_designer": {},
    "game_truck_rental": {},
    "golf_cart_rental": {},
    "henna_artist": {},
    "kids_recreation_and_party": {},
    "magician": {},
    "mohel": {},
    "musician": {},
    "officiating_services": {},
    "party_and_event_planning": {},
    "party_bike_rental": {},
    "party_bus_rental": {},
    "party_character": {},
    "personal_chef": {},
    "photo_booth_rental": {},
    "silent_disco": {},
    "sommelier_service": {},
    "team_building_activity": {},
    "trivia_host": {},
    "valet_service": {},
    "venue_and_event_space": {},
    "videographer": {},
    "wedding_chapel": {},
    "wedding_planning": {},
    "party_equipment_rental": {},
    "audiovisual_equipment_rental": {},
    "bounce_house_rental": {},
    "karaoke_rental": {},
    "photographer": {"craft": "photographer"},
    "boudoir_photography": {},
    "event_photography": {},
    "session_photography": {},
    "funeral_services_and_cemeteries": {},
    "cremation_services": {},
    "mortuary_services": {},
    "internet_service_provider": {},
    "web_hosting_service": {},
    "it_service_and_computer_repair": {},
    "data_recovery": {},
    "it_consultant": {},
    "it_support_snd_service": {},
    "mobile_phone_repair": {},
    "telecommunications": {},
    "junk_removal_and_hauling": {},
    "dumpster_rentals": {},
    "laundry_services": {},
    "dry_cleaning": {"shop": "laundry", "dry_cleaning": "yes"},
    "laundromat": {"shop": "laundry"},
    "legal_services": {},
    "court_reporter": {},
    "process_servers": {},
    "musical_instrument_services": {},
    "piano_services": {},
    "vocal_coach": {},
    "3d_printing_service": {},
    "acoustical_consultant": {},
    "adoption_services": {},
    "advertising_agency": {"office": "advertising_agency"},
    "copywriting_service": {},
    "internet_marketing_service": {},
    "merchandising_service": {},
    "social_media_agency": {},
    "after_school_program": {},
    "bank_equipment_service": {},
    "air_duct_cleaning_service": {},
    "antenna_service": {},
    "appliance_repair_service": {},
    "appraisal_services": {},
    "architect": {"office": "architect"},
    "architectural_designer": {},
    "art_restoration_service": {},
    "awning_supplier": {},
    "bail_bonds_service": {},
    "bike_repair_maintenance": {},
    "billing_services": {},
    "bookbinding": {},
    "bookkeeper": {},
    "bus_rentals": {},
    "business_consulting": {},
    "calligraphy": {},
    "car_broker": {},
    "career_counseling": {},
    "carpet_dyeing": {},
    "cemeteries": {},
    "certification_agency": {},
    "child_care_and_day_care": {},
    "day_care_preschool": {},
    "clock_repair_service": {},
    "commercial_printer": {},
    "commercial_refrigeration": {},
    "commissioned_artist": {},
    "community_book_boxes": {},
    "community_gardens": {},
    "computer_hardware_company": {},
    "courier_and_delivery_services": {},
    "crane_services": {},
    "customs_broker": {},
    "delegated_driver_service": {},
    "diamond_dealer": {},
    "digitizing_services": {},
    "donation_center": {},
    "duplication_services": {},
    "e_commerce_service": {},
    "editorial_services": {},
    "elder_care_planning": {},
    "electrical_consultant": {},
    "electronics_repair_shop": {},
    "elevator_service": {},
    "emergency_service": {},
    "employment_agencies": {},
    "temp_agency": {},
    "engraving": {},
    "environmental_abatement_services": {},
    "environmental_testing": {},
    "farm_equipment_repair_service": {},
    "feng_shui": {},
    "fingerprinting_service": {},
    "food_and_beverage_consultant": {},
    "forestry_service": {},
    "fortune_telling_service": {},
    "furniture_rental_service": {},
    "furniture_repair": {},
    "furniture_reupholstery": {},
    "genealogists": {},
    "generator_installation_repair": {},
    "goldsmith": {},
    "graphic_designer": {},
    "gunsmith": {},
    "hazardous_waste_disposal": {},
    "hydraulic_repair_service": {},
    "hydro_jetting": {},
    "ice_supplier": {},
    "immigration_assistance_services": {},
    "indoor_landscaping": {},
    "jewelry_repair_service": {},
    "junkyard": {},
    "knife_sharpening": {},
    "laboratory": {},
    "lawn_mower_repair_service": {},
    "life_coach": {},
    "lottery_ticket": {},
    "machine_and_tool_rentals": {},
    "machine_shop": {},
    "mailbox_center": {},
    "marketing_agency": {},
    "matchmaker": {},
    "mediator": {},
    "metal_detector_services": {},
    "misting_system_services": {},
    "mobility_equipment_services": {},
    "mooring_service": {},
    "music_production_services": {},
    "nanny_services": {},
    "notary_public": {},
    "package_locker": {},
    "packaging_contractors_and_service": {},
    "patent_law": {},
    "payroll_services": {},
    "personal_assistant": {},
    "pest_control_service": {},
    "powder_coating_service": {},
    "printing_services": {},
    "private_investigation": {},
    "product_design": {},
    "propane_supplier": {},
    "public_adjuster": {},
    "public_relations": {},
    "record_label": {},
    "recording_and_rehearsal_studio": {},
    "recycling_center": {},
    "sandblasting_service": {},
    "screen_printing_t_shirt_printing": {},
    "security_services": {},
    "septic_services": {},
    "shipping_center": {},
    "shoe_repair": {"shop": "shoe_repair"},
    "shoe_shining_service": {},
    "shredding_services": {},
    "sign_making": {},
    "snow_removal_service": {},
    "snuggle_service": {},
    "software_development": {},
    "talent_agency": {},
    "taxidermist": {},
    "telephone_services": {},
    "tenant_and_eviction_law": {},
    "tent_house_supplier": {},
    "translation_services": {},
    "tv_mounting": {},
    "typing_services": {},
    "video_film_production": {},
    "watch_repair_service": {},
    "water_delivery": {},
    "web_designer": {},
    "well_drilling": {},
    "wildlife_control": {},
    "writing_service": {},
    "storage_facility": {},
    "rv_and_boat_storage_facility": {},
    "boat_storage_facility": {},
    "rv_storage_facility": {},
    "self_storage_facility": {},
    "sewing_and_alterations": {},
    "gents_tailor": {},
    "utility_service": {},
    "electricity_supplier": {},
    "garbage_collection_service": {},
    "natural_gas_supplier": {},
    "public_phones": {},
    "public_restrooms": {},
    "water_supplier": {},
    "structure_and_geography": {"place": "yes"},
    "bridge": {"man_made": "bridge"},
    "canal": {"waterway": "canal"},
    "dam": {"waterway": "dam"},
    "desert": {},
    "forest": {},
    "geologic_formation": {},
    "island": {"place": "island"},
    "mountain": {"natural": "peak"},
    "natural_hot_springs": {},
    "nature_reserve": {"leisure": "nature_reserve"},
    "pier": {"man_made": "pier"},
    "public_plaza": {},
    "quay": {"man_made": "quay"},
    "river": {"waterway": "river"},
    "skyscraper": {},
    "tower": {},
    "weir": {"waterway": "weir"},
    "cafetaria": {"amenity": "fast_food", "fast_food": "cafeteria"},
}

print(unfilled | tags)
